// This file was automatically generated by lister-gen

package machine

// AWSMachineClassListerExpansion allows custom methods to be added to
// AWSMachineClassLister.
type AWSMachineClassListerExpansion interface{}

// AzureMachineClassListerExpansion allows custom methods to be added to
// AzureMachineClassLister.
type AzureMachineClassListerExpansion interface{}

// MachineListerExpansion allows custom methods to be added to
// MachineLister.
type MachineListerExpansion interface{}

// MachineDeploymentListerExpansion allows custom methods to be added to
// MachineDeploymentLister.
type MachineDeploymentListerExpansion interface{}

// MachineSetListerExpansion allows custom methods to be added to
// MachineSetLister.
type MachineSetListerExpansion interface{}

// MachineTemplateListerExpansion allows custom methods to be added to
// MachineTemplateLister.
type MachineTemplateListerExpansion interface{}

// MachineTemplateNamespaceListerExpansion allows custom methods to be added to
// MachineTemplateNamespaceLister.
type MachineTemplateNamespaceListerExpansion interface{}

// ScaleListerExpansion allows custom methods to be added to
// ScaleLister.
type ScaleListerExpansion interface{}

// ScaleNamespaceListerExpansion allows custom methods to be added to
// ScaleNamespaceLister.
type ScaleNamespaceListerExpansion interface{}
