// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	internalversion "github.com/gardener/machine-controller-manager/pkg/client/clientset/internalversion/typed/cluster/internalversion"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCluster struct {
	*testing.Fake
}

func (c *FakeCluster) Clusters(namespace string) internalversion.ClusterInterface {
	return &FakeClusters{c, namespace}
}

func (c *FakeCluster) Machines(namespace string) internalversion.MachineInterface {
	return &FakeMachines{c, namespace}
}

func (c *FakeCluster) MachineDeployments(namespace string) internalversion.MachineDeploymentInterface {
	return &FakeMachineDeployments{c, namespace}
}

func (c *FakeCluster) MachineSets(namespace string) internalversion.MachineSetInterface {
	return &FakeMachineSets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCluster) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
