version: "2"
run:
  concurrency: 4
linters:
  enable:
    - loggercheck
    - revive
  disable:
    - unused
  settings:
    loggercheck:
      logr: true
      zap: true
      no-printf-like: true
    revive:
      rules:
        - name: duplicated-imports
        - name: unused-parameter
        - name: unreachable-code
        - name: context-as-argument
        - name: early-return
        - name: exported
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: '(SA1019|QF1008|QF1003|ST1005):'
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: var-naming
      - path: (.+)\.go$
        text: dot-imports
      - path: (.+)\.go$
        text: package-comments
      - path: (.+)\.go$
        text: unexported-return
      - path: (.+)\.go$
        text: indent-error-flow
      - path: (.+)\.go$
        text: 'exported: (type|func) name will be used as .* by other packages, and that stutters;'
      - path: (.+)\.go$
        text: 'undeclared name: `.*`'
      - path: (.+)\.go$
        text: '".*" imported but not used'
      - path: (.+)\.go$
        text: 'structured logging message should be capitalized: "garden(er-apiserver|er-controller-manager|er-admission-controller|er-operator|er-resource-manager|let)'
    paths:
      - zz_generated\..*\.go$
      - pkg/client
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
