// This file was automatically generated by informer-gen

package internalversion

import (
	time "time"

	machine "github.com/gardener/node-controller-manager/pkg/apis/machine"
	clientset_internalversion "github.com/gardener/node-controller-manager/pkg/client/clientset/internalversion"
	internalinterfaces "github.com/gardener/node-controller-manager/pkg/client/informers/internalversion/internalinterfaces"
	internalversion "github.com/gardener/node-controller-manager/pkg/client/listers/machine/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureMachineClassInformer provides access to a shared informer and lister for
// AzureMachineClasses.
type AzureMachineClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.AzureMachineClassLister
}

type azureMachineClassInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAzureMachineClassInformer constructs a new informer for AzureMachineClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureMachineClassInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureMachineClassInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAzureMachineClassInformer constructs a new informer for AzureMachineClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureMachineClassInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Machine().AzureMachineClasses().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Machine().AzureMachineClasses().Watch(options)
			},
		},
		&machine.AzureMachineClass{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureMachineClassInformer) defaultInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureMachineClassInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureMachineClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&machine.AzureMachineClass{}, f.defaultInformer)
}

func (f *azureMachineClassInformer) Lister() internalversion.AzureMachineClassLister {
	return internalversion.NewAzureMachineClassLister(f.Informer().GetIndexer())
}
