// This file was automatically generated by informer-gen

package internalversion

import (
	machine "github.com/gardener/node-controller-manager/pkg/apis/machine"
	internalinterfaces "github.com/gardener/node-controller-manager/pkg/client/informers/internalversion/internalinterfaces"
	internalclientset "github.com/gardener/node-controller-manager/pkg/client/internalclientset"
	internalversion "github.com/gardener/node-controller-manager/pkg/client/listers/machine/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// GCPMachineClassInformer provides access to a shared informer and lister for
// GCPMachineClasses.
type GCPMachineClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.GCPMachineClassLister
}

type gCPMachineClassInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewGCPMachineClassInformer constructs a new informer for GCPMachineClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGCPMachineClassInformer(client internalclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.Machine().GCPMachineClasses().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.Machine().GCPMachineClasses().Watch(options)
			},
		},
		&machine.GCPMachineClass{},
		resyncPeriod,
		indexers,
	)
}

func defaultGCPMachineClassInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewGCPMachineClassInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *gCPMachineClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&machine.GCPMachineClass{}, defaultGCPMachineClassInformer)
}

func (f *gCPMachineClassInformer) Lister() internalversion.GCPMachineClassLister {
	return internalversion.NewGCPMachineClassLister(f.Informer().GetIndexer())
}
