apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: machine-controller-manager-control
rules:
-  apiGroups:
   - machine.sapcloud.io
   resources:
   - awsmachineclasses
   - azuremachineclasses
   - gcpmachineclasses
   - openstackmachineclasses
   - alicloudmachineclasses
   - packetmachineclasses
   - machinedeployments
   - machines
   - machinesets
   verbs:
   - create
   - delete
   - deletecollection
   - get
   - list
   - patch
   - update
   - watch
-  apiGroups:
   - ""
   resources:
   - nodes
   - nodes/status
   - configmaps
   - secrets
   - events
   verbs:
   - create
   - delete
   - deletecollection
   - get
   - list
   - patch
   - update
   - watch
-  apiGroups:
   - coordination.k8s.io
   resources:
   - leases
   verbs:
   - create
-  apiGroups:
   - coordination.k8s.io
   resources:
   - leases
   resourceNames:
   - machine-controller-manager
   verbs:
   - get
   - watch
   - update
