// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package internalversion

type MachineExpansion interface{}

type MachineClassExpansion interface{}

type MachineDeploymentExpansion interface{}

type MachineSetExpansion interface{}

type MachineTemplateExpansion interface{}
