apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: node-controller-manager
rules:
- apiGroups:
  - "machine.sapcloud.io"
  resources:
  - awsmachineclasses
  - azuremachineclasses
  - gcpmachineclasses
  - machinedeployments
  - machines
  - machinesets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - configmaps
  - secrets
  - serviceaccounts
  - endpoints
  - events
  - namespaces
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - list
  - watch
