# Sample secret

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # Alicloud cloud config file (base64 encoded)
  alicloudAccessKeyID: "alicloud-access-key-id" # Alicloud access key ID (base64 encoded)
  alicloudAccessKeySecret: "alicloud-access-key-secret" # Alicloud secret access key (base64 encoded)
### Alternative data keys are:
# accessKeyID: "alicloud-access-key-id" # Alicloud access key ID (base64 encoded)
# accessKeySecret: "alicloud-access-key-secret" # Alicloud secret access key (base64 encoded)
type: Opaque
