# Sample secret

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # AWS cloud config file (base64 encoded)
  providerAccessKeyId: "pqrstu67890" # AWS access key id (base64 encoded)
  providerSecretAccessKey: "abcdef123456" # AWS secret access key (base64 encoded)
type: Opaque
