# Sample OpenStack secret

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data: # base64 encoded
  userData: <cloud_init> # Cloud init file for used by the machines
  authURL: <auth_URL> # Keystone auth endpoint address
  username: <username> # Keystone username
  password: <password> # Keystone password
  domainName: <domain_name> # Keystone domain name
  # domainID: <domain_id> # Keystone domaine id (optional)
  tenantName: <tenant_name> # Keystone tenant name
  # tenantID: <tenant_id> # Keystone tenant id (optional)
  # userDomainName: <user_domain_name> # Keystone user domain name (optional)
  # userDomainID: <user_domain_id> # Keystone user domain id (optional)
  insecure: "true" # | "false" # optional: if running against a self signed OpenStack endpoints
  # optional certificate/autherization block
  caCert: <caCert> # Custom certificate of your OpenStack endpoints
  clientCert: <clientCert> # Client certificate
  clientKey: <clientKey> # Client jey
type: Opaque
