// This file was automatically generated by informer-gen

package internalversion

import (
	node "code.sapcloud.io/kubernetes/node-controller-manager/pkg/apis/node"
	internalinterfaces "code.sapcloud.io/kubernetes/node-controller-manager/pkg/client/informers/internalversion/internalinterfaces"
	internalclientset "code.sapcloud.io/kubernetes/node-controller-manager/pkg/client/internalclientset"
	internalversion "code.sapcloud.io/kubernetes/node-controller-manager/pkg/client/listers/node/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// InstanceDeploymentInformer provides access to a shared informer and lister for
// InstanceDeployments.
type InstanceDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.InstanceDeploymentLister
}

type instanceDeploymentInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewInstanceDeploymentInformer constructs a new informer for InstanceDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInstanceDeploymentInformer(client internalclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.Node().InstanceDeployments().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.Node().InstanceDeployments().Watch(options)
			},
		},
		&node.InstanceDeployment{},
		resyncPeriod,
		indexers,
	)
}

func defaultInstanceDeploymentInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewInstanceDeploymentInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *instanceDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&node.InstanceDeployment{}, defaultInstanceDeploymentInformer)
}

func (f *instanceDeploymentInformer) Lister() internalversion.InstanceDeploymentLister {
	return internalversion.NewInstanceDeploymentLister(f.Informer().GetIndexer())
}
