// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	v1alpha1 "github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
	machinev1alpha1 "github.com/gardener/machine-controller-manager/pkg/client/clientset/versioned/typed/machine/v1alpha1"
	v1 "k8s.io/api/autoscaling/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
)

// fakeMachineSets implements MachineSetInterface
type fakeMachineSets struct {
	*gentype.FakeClientWithList[*v1alpha1.MachineSet, *v1alpha1.MachineSetList]
	Fake *FakeMachineV1alpha1
}

func newFakeMachineSets(fake *FakeMachineV1alpha1, namespace string) machinev1alpha1.MachineSetInterface {
	return &fakeMachineSets{
		gentype.NewFakeClientWithList[*v1alpha1.MachineSet, *v1alpha1.MachineSetList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("machinesets"),
			v1alpha1.SchemeGroupVersion.WithKind("MachineSet"),
			func() *v1alpha1.MachineSet { return &v1alpha1.MachineSet{} },
			func() *v1alpha1.MachineSetList { return &v1alpha1.MachineSetList{} },
			func(dst, src *v1alpha1.MachineSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MachineSetList) []*v1alpha1.MachineSet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.MachineSetList, items []*v1alpha1.MachineSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *fakeMachineSets) UpdateScale(ctx context.Context, machineSetName string, scale *v1.Scale, opts metav1.UpdateOptions) (result *v1.Scale, err error) {
	emptyResult := &v1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(c.Resource(), "scale", c.Namespace(), scale, opts), &v1.Scale{})

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Scale), err
}
