#!/usr/bin/env bash

# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mkdir -p dev
mkdir -p logs

declare -a cloud_providers=("aws" "az" "gcp" "os")
failed_logs=""

aws_control_kubeconfig=dev/aws_control_kubeconfig.yaml
aws_target_kubeconfig=dev/aws_target_kubeconfig.yaml
az_control_kubeconfig=dev/az_control_kubeconfig.yaml
az_target_kubeconfig=dev/az_target_kubeconfig.yaml
gcp_control_kubeconfig=dev/gcp_control_kubeconfig.yaml
gcp_target_kubeconfig=dev/gcp_target_kubeconfig.yaml
os_control_kubeconfig=dev/os_control_kubeconfig.yaml
os_target_kubeconfig=dev/os_target_kubeconfig.yaml

/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-aws-control --key kubeconfig > $aws_control_kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-aws-target --key kubeconfig > $aws_target_kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-az-control --key kubeconfig > $az_control_kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-az-target --key kubeconfig > $az_target_kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-gcp-control --key kubeconfig > $gcp_control_kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-gcp-target --key kubeconfig > $gcp_target_kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-os-control --key kubeconfig > $os_control_kubeconfig
/cc/utils/cli.py config attribute --cfg-type kubernetes --cfg-name mcm-ci-os-target --key kubeconfig > $os_target_kubeconfig
Objects_path=$SOURCE_PATH/.ci/sample-objects
num_of_existing_nodes=1

############################################## <Initialization> ##############################################

function check_cluster_state() {
    printf "\t\t\t----- Checking Test Environment -------\n"

    printf "\nChecking existance of machine objects\n"
    # Wait 20mins for any existing PRs to cleanup machines
    hf_wait_on "hf_num_of_objects" mach 0 1200
    printf "No machine objects in target test cluster\n"

    printf "\nChecking existance of node objects\n"
    # Wait 20mins for any existing PRs to cleanup nodes
    hf_wait_on "hf_num_of_ready_nodes" nodes 0 1200
    printf "No additional node objects in target test cluster\n"

    printf "\nCluster state looks clean\n"
}

function setup_environment() {
    printf "\n\t\t\t----- Setup Test Environment --------\n"

    printf "\nDownloading and installing kubectl\n"
    curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin/kubectl
    printf "Successfully installed kubectl\n"

    printf "\nBuilding MCM binary\n"
    if go build -i cmd/machine-controller-manager/controller_manager.go; then
        printf "Go build Successful\n"
    else
        printf "Go build Failure\n"
        terminate_script
    fi
}

# run_controller runs MCM controller in background
# it expects 3 parameters
# 1 - control cluster kubeconfig
# 2 - target cluster kubeconfig
# 3 - port to which wish to bind the controller
function run_controller() {
    printf "\nRunning MCM in background\n"
    ./controller_manager \
        --control-kubeconfig=$1 \
        --target-kubeconfig=$2 \
        --namespace=$provider \
        --port=$3 \
        --safety-up=2 \
        --safety-down=1 \
        --machine-drain-timeout=5 \
        --machine-health-timeout=10 \
        --machine-set-scale-timeout=20 \
        --v=2 > logs/${provider}-mcm.out 2>&1 &
}

############################################## </Intialization> ##############################################
############################################## <HelperFunction> ##############################################

function hf_object_create() {
    output=$(kubectl apply -f "$Objects_path"/"$1" --context=control 2>&1)
    outputSucccess=$(echo "$output" | grep created -c)
    if [[ outputSucccess -ne 1 ]]; then
        printf "\tFailed: To create object. Exiting Test to avoid further conflicts.\n"
        printf "\tCreate error message: %s" "$output"
        terminate_script
    fi

    printf "\n\t%s" "$output"
}

function hf_object_configure() {
    output=$(kubectl apply -f "$Objects_path"/"$1" --context=control 2>&1)
    outputSucccess=$(echo "$output" | grep configured -c)
    if [[ outputSucccess -ne 1 ]]; then
        printf "\tFailed: To apply object. Exiting Test to avoid further conflicts.\n"
        printf "\tApply error message: %s" "$output"
        terminate_script
    fi

    printf "\n\t%s" "$output"
}

function hf_object_delete() {
    output=$(kubectl delete -f "$Objects_path"/"$1" --context=control 2>&1)
    outputSucccess=$(echo "$output" | grep deleted -c)
    if [[ outputSucccess -ne 1 ]]; then
        printf "\tFailed: To delete object. Exiting Test to avoid further conflicts.\n"
        printf "\tDelete error message: %s" "$output"
        terminate_script
    fi

    printf "\n\t%s" "$output"
}

function hf_scale_deploy() {
    output=$(kubectl scale deployment "$1" --replicas="$2" --context=control --namespace="$provider" 2>&1)
    outputSucccess=$(echo "$output" | grep scaled -c)
    if [[ outputSucccess -ne 1 ]]; then
        printf "\tFailed: To scale deployment object. Exiting Test to avoid further conflicts.\n"
        printf "\tScale error message: %s" "$output"
        printf "Clean-up script for $provider has failed. Kindly manually cleanup the cluster"
    fi
}

function hf_num_of_objects() {
    output=$(kubectl -n $provider get "$1" --context=control 2>&1)
    if [[ $output == *"No resources found."* ]]; then
        return 0
    fi
    object_count=$(echo "$output" | wc -l)
    ((object_count--))

    return "$object_count"
}

function hf_num_of_ready_nodes() {
    output=$(kubectl get "$1" --context=target 2>&1)
    ready_count=$(echo "$output" | tr " " "\n" | grep ^Ready -c)

    return $((ready_count-num_of_existing_nodes))
}

function hf_wait_on() {
    function_name=$1
    function_param=$2
    count_to_match=$3
    seconds_to_wait=$4
    iteration_count=$(($seconds_to_wait/30))

    while
        "$function_name" "$function_param"
        ret=$?
        [[ $ret -ne $count_to_match ]]
    do
        sleep 30
        ((iteration_count--))

        # Exit script when timeout occurs
        if [ $iteration_count -le 0 ]; then
            printf "\tFailed: Timeout occured while waiting for operation. Exiting Test to avoid further conflicts.\n"
            printf "\tExecuting function: %s, %s" $function_name $function_param
            if [ -z "$5" ]; then
                terminate_script
            fi
        fi

    done
}

function terminate_script() {
    printf "\n\t\t\t----- Start of MCM Logs for $provider -----------\n"
    cat logs/${provider}-mcm.out
    printf "\n\t\t\t----- End of MCM logs for $provider -----------\n\n"
    printf "CI tests have failed for $provider. Re-check your PR."
    exit 1
}

############################################## </HelperFunction> #############################################
############################################## <TestCases> ###################################################
function tc_machine() {

    printf "\nStarting TestCase: %s" "${FUNCNAME[0]}"

    # Wait until 1 nodes have joined the cluster
    hf_object_create $provider/machine.yaml
    printf "\n\tWaiting 1200s for machine to join the cluster"
    hf_wait_on "hf_num_of_ready_nodes" nodes 1 1200

    # Wait for deletion of machine
    hf_object_delete $provider/machine.yaml
    printf "\n\tWaiting 1200s for machine to be deleted"
    hf_wait_on "hf_num_of_objects" mach 0 1200

    printf "\nCompleted TestCase\n"
}

function tc_machine_deployment() {

    printf "\nStarting TestCase: %s" "${FUNCNAME[0]}"

    # Wait until 3 nodes have joined the cluster
    hf_object_create $provider/md.yaml
    printf "\n\tWaiting 1200s for 3 machines to join the cluster"
    hf_wait_on "hf_num_of_ready_nodes" nodes 3 1200

    # Scale down the number of nodes to 2
    hf_object_configure $provider/md-scale-down.yaml
    printf "\n\tWaiting 1200s for machines to scale-down to 2"
    hf_wait_on "hf_num_of_ready_nodes" nodes 2 1200

    # Update the machines to v2 and double the number of replicas
    hf_object_configure $provider/md-update.yaml
    printf "\n\tWaiting 2400s for machines to upgrade to larger machine types and scale-up replicas to 4"
    hf_wait_on "hf_num_of_ready_nodes" nodes 4 2400

    # Delete the machine-deployment
    hf_object_delete $provider/md.yaml
    printf "\n\tWaiting 1200s for machine to be deleted"
    hf_wait_on "hf_num_of_objects" machdeploy 0 1200

    printf "\nCompleted TestCase\n"
}

############################################## </TestCases> ##################################################
############################################## <CleanUp> #####################################################

function clean_up() {
    provider=$1
    export KUBECONFIG=$2:$3

    printf "\n\t\t\t----- CleanUp Test Environment -----\n"
    hf_scale_deploy machine-controller-manager 1

    if
        hf_num_of_objects machdeploy 0
        ret=$?
        [[ $ret -ne 0 ]]
    then
        # Delete the machine-deployment
        hf_object_delete $provider/md.yaml
        printf "\n\tWaiting 1200s for machine-deployment to be deleted"
        hf_wait_on "hf_num_of_objects" machdeploy 0 1200 $5
    fi

    if
        hf_num_of_objects mach 0
        ret=$?
        [[ $ret -ne 0 ]]
    then
        # Delete the machine
        hf_object_delete $provider/machine.yaml
        printf "\n\tWaiting 1200s for machine to be deleted"
        hf_wait_on "hf_num_of_objects" mach 0 1200 $5
    fi

    hf_scale_deploy machine-controller-manager 0
    printf "\n\t\t\t----- End of CleanUp Test Environment -----\n"
}

function test_cloud_provider() {
    provider=$1
    export KUBECONFIG=$2:$3

    run_controller $2 $3 $4
    check_cluster_state

    printf "\n\t\t\t----- Start of TestCases -----------\n"

    tc_machine
    tc_machine_deployment
    sleep 30

    printf "\n\t\t\t----- End of TestCases -------------\n"

    printf "\n\t\t\t----- Start of MCM Logs for $provider -----------\n"
    cat logs/${provider}-mcm.out
    printf "\n\t\t\t----- End of MCM logs for $provider -----------\n"
}

function test_all_providers() {
    test_cloud_provider "aws" $aws_control_kubeconfig $aws_target_kubeconfig 10258 > logs/aws-it.out & pids[0]=$!
    test_cloud_provider "az" $az_control_kubeconfig $az_target_kubeconfig 10259 > logs/az-it.out & pids[1]=$!
    test_cloud_provider "gcp" $gcp_control_kubeconfig $gcp_target_kubeconfig 10260 > logs/gcp-it.out & pids[2]=$!
    test_cloud_provider "os" $os_control_kubeconfig $os_target_kubeconfig 10261 > logs/os-it.out & pids[3]=$!

    # wait for all pids
    for pid in ${pids[*]}; do
        printf "\nWaiting for integration tests to complete"
        wait $pid
    done
}

function cleanup_all_providers() {
    clean_up "aws" $aws_control_kubeconfig $aws_target_kubeconfig > logs/aws-cleanup.out & pids[0]=$!
    clean_up "az" $az_control_kubeconfig $az_target_kubeconfig > logs/az-cleanup.out & pids[1]=$!
    clean_up "gcp" $gcp_control_kubeconfig $gcp_target_kubeconfig > logs/gcp-cleanup.out & pids[2]=$!
    clean_up "os" $os_control_kubeconfig $os_target_kubeconfig > logs/os-cleanup.out & pids[3]=$!

    # wait for all pids
    for pid in ${pids[*]}; do
        printf "\nWaiting for clean-up to complete"
        wait $pid
    done
}

function print_logs() {
    for cp in "${cloud_providers[@]}"; do
        printf "\n\t\t\t----- Start of Integration Test Logs for $cp -----------\n"
        cat logs/${cp}-it.out
        printf "\n\t\t\t----- End of Integration Test logs for $cp -----------\n"

        output=$(cat logs/${cp}-it.out)
        if [[ $output == *"CI tests have failed for"* ]]; then
            failed_logs="${failed_logs}\n\t- ${cp}"

            printf "\n\t\t\t----- Start of Clean-Up Logs for $cp -----------\n"
            cat logs/${cp}-cleanup.out
            printf "\n\t\t\t----- End of Clean-Up logs for $cp -----------\n"
        fi
    done
}

function print_results() {
    if [[ $failed_logs != "" ]]; then
        printf "\n\t\t\t----- Test failure logs -----------\n"
        printf "Integration test for the following cloud providers have failed. Kindly re-check your PR."
        printf $failed_logs
        printf "\n\t\t\t----- End of Test failure logs -----------\n"
        exit 1
    else
        printf "CI tests passed successfully"
    fi
}

############################################## </CleanUp> ####################################################
############################################## <Main> ########################################################

printf "\n\t\t\t----- Start of Test Script -----------\n"

setup_environment
test_all_providers
cleanup_all_providers
print_logs
pkill controller_manager
print_results

printf "\n\t\t\t----- End of Test Script -----------\n"

############################################## </Main> #######################################################
