apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlConfiguration
options:
  runtime: binary
  kubeVersion: v1.35.0
  # disableKubeControllerManager: true
  nodeLeaseDurationSeconds: 20
  kubeControllerManagerNodeMonitorPeriodMilliseconds: 15000
  kubeControllerManagerNodeMonitorGracePeriodMilliseconds: 20000
  heartbeatFactor: 1
  manageAllNodes: true
componentsPatches:
  - name: kube-controller-manager
    extraArgs:
    - key: leader-elect
      value: "false"
  - name: kube-apiserver
    extraArgs:
    - key: disable-admission-plugins
      value: "TaintNodesByCondition"

## These are the default stages added by kwok when `enableCRDs : "stage"` isn't used
## They're reproduced here to ensure that pod/node lifecycles can be mimiced exactly.

## There is an additional stage added called `node-recover` that sets a node's Ready
## condition back to True if its annotated with `kwok/fail-condition=Recover`.

## TODO(@takoverflow): see if the `node-initialize` stage should be removed since
## simulatedprovider `CreateMachine` call also handles transitioning the node to `Ready`
---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-initialize
spec:
  immediateNextStage: false
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $lastTransitionTime := or .metadata.creationTimestamp $now }}
      conditions:
      {{ range NodeConditions }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $lastTransitionTime | Quote }}
        message: {{ .message | Quote }}
        reason: {{ .reason | Quote }}
        status: {{ .status | Quote }}
        type: {{ .type  | Quote}}
      {{ end }}

      {{ $hasInternalIP := false }}
      {{ $hasHostname := false }}
      {{ range .status.addresses }}
        {{ if eq .type "InternalIP" }}
          {{ $hasInternalIP = true }}
        {{ end }}
        {{ if eq .type "Hostname" }}
          {{ $hasHostname = true }}
        {{ end }}
      {{ end }}
      {{ if or (not $hasInternalIP) (not $hasHostname) }}
      addresses:
      {{ end }}
      {{ if not $hasInternalIP }}
      {{ with NodeIP }}
      - address: {{ . | Quote }}
        type: InternalIP
      {{ end }}
      {{ end }}
      {{ if not $hasHostname }}
      {{ with NodeName }}
      - address: {{ . | Quote }}
        type: Hostname
      {{ end }}
      {{ end }}

      {{ with NodePort }}
      daemonEndpoints:
        kubeletEndpoint:
          Port: {{ . }}
      {{ end }}

      allocatable:
      {{ with .status.allocatable }}
      {{ YAML . 1 }}
      {{ else }}
        cpu: 1k
        memory: 1Ti
        pods: 1M
      {{ end }}
      capacity:
      {{ with .status.capacity }}
      {{ YAML . 1 }}
      {{ else }}
        cpu: 1k
        memory: 1Ti
        pods: 1M
      {{ end }}

      {{ $nodeInfo := .status.nodeInfo }}
      {{ $kwokVersion := printf "kwok-%s" Version }}
      nodeInfo:
        architecture: {{ or $nodeInfo.architecture "amd64" }}
        bootID: {{ or $nodeInfo.bootID `""` }}
        containerRuntimeVersion: {{ or $nodeInfo.containerRuntimeVersion $kwokVersion }}
        kernelVersion: {{ or $nodeInfo.kernelVersion $kwokVersion }}
        kubeProxyVersion: {{ or $nodeInfo.kubeProxyVersion $kwokVersion }}
        kubeletVersion: {{ or $nodeInfo.kubeletVersion $kwokVersion }}
        machineID: {{ or $nodeInfo.machineID `""` }}
        operatingSystem: {{ or $nodeInfo.operatingSystem "linux" }}
        osImage: {{ or $nodeInfo.osImage `""` }}
        systemUUID: {{ or $nodeInfo.systemUUID `""` }}
      phase: Running
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - jq:
        key: .status.conditions.[] | select( .type == "Ready" ) | .status
        operator: NotIn
        values:
        - "True"
  steps:
  - patch:
      root: status
      subresource: status
      template: |
        {{ $now := Now }}
        {{ $lastTransitionTime := or .metadata.creationTimestamp $now }}
        conditions:
        {{ range NodeConditions }}
        - lastHeartbeatTime: {{ $now | Quote }}
          lastTransitionTime: {{ $lastTransitionTime | Quote }}
          message: {{ .message | Quote }}
          reason: {{ .reason | Quote }}
          status: {{ .status | Quote }}
          type: {{ .type  | Quote}}
        {{ end }}

        {{ $hasInternalIP := false }}
        {{ $hasHostname := false }}
        {{ range .status.addresses }}
          {{ if eq .type "InternalIP" }}
            {{ $hasInternalIP = true }}
          {{ end }}
          {{ if eq .type "Hostname" }}
            {{ $hasHostname = true }}
          {{ end }}
        {{ end }}
        {{ if or (not $hasInternalIP) (not $hasHostname) }}
        addresses:
        {{ end }}
        {{ if not $hasInternalIP }}
        {{ with NodeIP }}
        - address: {{ . | Quote }}
          type: InternalIP
        {{ end }}
        {{ end }}
        {{ if not $hasHostname }}
        {{ with NodeName }}
        - address: {{ . | Quote }}
          type: Hostname
        {{ end }}
        {{ end }}

        {{ with NodePort }}
        daemonEndpoints:
          kubeletEndpoint:
            Port: {{ . }}
        {{ end }}

        allocatable:
        {{ with .status.allocatable }}
        {{ YAML . 1 }}
        {{ else }}
          cpu: 1k
          memory: 1Ti
          pods: 1M
        {{ end }}
        capacity:
        {{ with .status.capacity }}
        {{ YAML . 1 }}
        {{ else }}
          cpu: 1k
          memory: 1Ti
          pods: 1M
        {{ end }}

        {{ $nodeInfo := .status.nodeInfo }}
        {{ $kwokVersion := printf "kwok-%s" Version }}
        nodeInfo:
          architecture: {{ or $nodeInfo.architecture "amd64" }}
          bootID: {{ or $nodeInfo.bootID `""` }}
          containerRuntimeVersion: {{ or $nodeInfo.containerRuntimeVersion $kwokVersion }}
          kernelVersion: {{ or $nodeInfo.kernelVersion $kwokVersion }}
          kubeProxyVersion: {{ or $nodeInfo.kubeProxyVersion $kwokVersion }}
          kubeletVersion: {{ or $nodeInfo.kubeletVersion $kwokVersion }}
          machineID: {{ or $nodeInfo.machineID `""` }}
          operatingSystem: {{ or $nodeInfo.operatingSystem "linux" }}
          osImage: {{ or $nodeInfo.osImage `""` }}
          systemUUID: {{ or $nodeInfo.systemUUID `""` }}
        phase: Running
status: {}

---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-heartbeat-with-lease
spec:
  delay:
    durationMilliseconds: 60000
    jitterDurationMilliseconds: 61000
  immediateNextStage: false
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $lastTransitionTime := or .metadata.creationTimestamp $now }}
      conditions:
      {{ range NodeConditions }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $lastTransitionTime | Quote }}
        message: {{ .message | Quote }}
        reason: {{ .reason | Quote }}
        status: {{ .status | Quote }}
        type: {{ .type | Quote }}
      {{ end }}

      addresses:
      {{ with .status.addresses }}
      {{ YAML . 1 }}
      {{ else }}
      {{ with NodeIP }}
      - address: {{ . | Quote }}
        type: InternalIP
      {{ end }}
      {{ with NodeName }}
      - address: {{ . | Quote }}
        type: Hostname
      {{ end }}
      {{ end }}

      {{ with NodePort }}
      daemonEndpoints:
        kubeletEndpoint:
          Port: {{ . }}
      {{ end }}
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - jq:
        key: .status.phase
        operator: In
        values:
        - Running
    - jq:
        key: .status.conditions.[] | select( .type == "Ready" ) | .status
        operator: In
        values:
        - "True"
  steps:
  - patch:
      root: status
      subresource: status
      template: |
        {{ $now := Now }}
        {{ $lastTransitionTime := or .metadata.creationTimestamp $now }}
        conditions:
        {{ range NodeConditions }}
        - lastHeartbeatTime: {{ $now | Quote }}
          lastTransitionTime: {{ $lastTransitionTime | Quote }}
          message: {{ .message | Quote }}
          reason: {{ .reason | Quote }}
          status: {{ .status | Quote }}
          type: {{ .type | Quote }}
        {{ end }}

        addresses:
        {{ with .status.addresses }}
        {{ YAML . 1 }}
        {{ else }}
        {{ with NodeIP }}
        - address: {{ . | Quote }}
          type: InternalIP
        {{ end }}
        {{ with NodeName }}
        - address: {{ . | Quote }}
          type: Hostname
        {{ end }}
        {{ end }}

        {{ with NodePort }}
        daemonEndpoints:
          kubeletEndpoint:
            Port: {{ . }}
        {{ end }}
status: {}

---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-recover
spec:
  delay:
    durationMilliseconds: 5000
    jitterDurationMilliseconds: 6000
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
      - key: '.metadata.annotations["kwok/fail-condition"]'
        operator: 'In'
        values:
        - 'Recover'
  next:
   statusTemplate: |
     {{- $now := Now }}
     conditions:
     {{- range $index, $item := .status.conditions }}
     {{- if eq $item.type "Ready" }}
     - lastHeartbeatTime: {{ $now | Quote }}
       lastTransitionTime: {{ $now | Quote }}
       message: ""
       reason: ""
       status: "True"
       type: {{ $item.type | Quote }}
     {{ else }}
     - lastHeartbeatTime: {{ $now | Quote }}
       lastTransitionTime: {{ $now | Quote }}
       message: ""
       reason: ""
       status: "False"
       type: {{ $item.type | Quote }}
     {{- end }}
     {{- end }}
     addresses: {{ .status.addresses | toJson }}
     allocatable: {{ .status.allocatable | toJson }}
     capacity: {{ .status.capacity | toJson }}
     nodeInfo: {{ .status.nodeInfo | toJson }}

---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-ready
spec:
  immediateNextStage: false
  next:
    statusTemplate: |
      {{ $now := Now }}

      conditions:
      - lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: Initialized
      - lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: Ready
      - lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: ContainersReady
      {{ range .spec.readinessGates }}
      - lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: {{ .conditionType | Quote }}
      {{ end }}

      containerStatuses:
      {{ range .spec.containers }}
      - image: {{ .image | Quote }}
        name: {{ .name | Quote }}
        ready: true
        restartCount: 0
        state:
          running:
            startedAt: {{ $now | Quote }}
      {{ end }}

      initContainerStatuses:
      {{ range .spec.initContainers }}
      - image: {{ .image | Quote }}
        name: {{ .name | Quote }}
        ready: true
        restartCount: 0
        {{ if eq .restartPolicy "Always" }}
        started: true
        state:
          running:
            startedAt: {{ $now | Quote }}
        {{ else }}
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ $now | Quote }}
            reason: Completed
            startedAt: {{ $now | Quote }}
        {{ end }}
      {{ end }}
      {{ $hostIPs := NodeIPsWith .spec.nodeName }}
      {{ with $hostIPs }}
      hostIP: {{ index . 0 | Quote }}
      hostIPs:
      {{ range . }}
      - ip: {{ . | Quote }}
      {{ end }}
      {{ end }}
      {{ $podIPs := PodIPsWith .spec.nodeName ( or .spec.hostNetwork false ) ( or .metadata.uid "" ) ( or .metadata.name "" ) ( or .metadata.namespace "" ) }}
      {{ with $podIPs }}
      podIP: {{ index . 0 | Quote }}
      podIPs:
      {{ range . }}
      - ip: {{ . | Quote }}
      {{ end }}
      {{ end }}
      phase: Running
      startTime: {{ $now | Quote }}
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.phase
        operator: In
        values:
        - Pending
    - jq:
        key: .status.conditions.[] | select( .type == "Ready" ) | .status
        operator: NotIn
        values:
        - "True"
  steps:
  - patch:
      root: status
      subresource: status
      template: |
        {{ $now := Now }}

        conditions:
        - lastTransitionTime: {{ $now | Quote }}
          status: "True"
          type: Initialized
        - lastTransitionTime: {{ $now | Quote }}
          status: "True"
          type: Ready
        - lastTransitionTime: {{ $now | Quote }}
          status: "True"
          type: ContainersReady
        {{ range .spec.readinessGates }}
        - lastTransitionTime: {{ $now | Quote }}
          status: "True"
          type: {{ .conditionType | Quote }}
        {{ end }}

        containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image | Quote }}
          name: {{ .name | Quote }}
          ready: true
          restartCount: 0
          state:
            running:
              startedAt: {{ $now | Quote }}
        {{ end }}

        initContainerStatuses:
        {{ range .spec.initContainers }}
        - image: {{ .image | Quote }}
          name: {{ .name | Quote }}
          ready: true
          restartCount: 0
          {{ if eq .restartPolicy "Always" }}
          started: true
          state:
            running:
              startedAt: {{ $now | Quote }}
          {{ else }}
          state:
            terminated:
              exitCode: 0
              finishedAt: {{ $now | Quote }}
              reason: Completed
              startedAt: {{ $now | Quote }}
          {{ end }}
        {{ end }}
        {{ $hostIPs := NodeIPsWith .spec.nodeName }}
        {{ with $hostIPs }}
        hostIP: {{ index . 0 | Quote }}
        hostIPs:
        {{ range . }}
        - ip: {{ . | Quote }}
        {{ end }}
        {{ end }}
        {{ $podIPs := PodIPsWith .spec.nodeName ( or .spec.hostNetwork false ) ( or .metadata.uid "" ) ( or .metadata.name "" ) ( or .metadata.namespace "" ) }}
        {{ with $podIPs }}
        podIP: {{ index . 0 | Quote }}
        podIPs:
        {{ range . }}
        - ip: {{ . | Quote }}
        {{ end }}
        {{ end }}
        phase: Running
        startTime: {{ $now | Quote }}
status: {}

---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-complete
spec:
  immediateNextStage: false
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      containerStatuses:
      {{ range $index, $item := .spec.containers }}
      {{ $origin := index $root.status.containerStatuses $index }}
      - image: {{ $item.image | Quote }}
        name: {{ $item.name | Quote }}
        ready: false
        restartCount: 0
        started: false
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ $now | Quote }}
            reason: Completed
            startedAt: {{ $now | Quote }}
      {{ end }}
      phase: Succeeded
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: DoesNotExist
    - jq:
        key: .status.phase
        operator: In
        values:
        - Running
    - jq:
        key: .metadata.ownerReferences.[].kind
        operator: In
        values:
        - Job
  steps:
  - patch:
      root: status
      subresource: status
      template: |
        {{ $now := Now }}
        {{ $root := . }}
        containerStatuses:
        {{ range $index, $item := .spec.containers }}
        {{ $origin := index $root.status.containerStatuses $index }}
        - image: {{ $item.image | Quote }}
          name: {{ $item.name | Quote }}
          ready: false
          restartCount: 0
          started: false
          state:
            terminated:
              exitCode: 0
              finishedAt: {{ $now | Quote }}
              reason: Completed
              startedAt: {{ $now | Quote }}
        {{ end }}
        phase: Succeeded
status: {}

---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-delete
spec:
  immediateNextStage: false
  next:
    delete: true
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - jq:
        key: .metadata.deletionTimestamp
        operator: Exists
  steps:
  - delete: true
status: {}
