// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra.proto

package infra

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The message containing driver side structures
type DriverSide struct {
	// operationID to match response with asynchronous requests
	OperationID int32 `protobuf:"varint,1,opt,name=operationID" json:"operationID,omitempty"`
	// operationType can be register, create, delete, getVMs
	OperationType string `protobuf:"bytes,2,opt,name=operationType" json:"operationType,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*DriverSide_RegisterResp
	//	*DriverSide_Createresponse
	//	*DriverSide_Deleteresponse
	//	*DriverSide_Listresponse
	Response             isDriverSide_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DriverSide) Reset()         { *m = DriverSide{} }
func (m *DriverSide) String() string { return proto.CompactTextString(m) }
func (*DriverSide) ProtoMessage()    {}
func (*DriverSide) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{0}
}
func (m *DriverSide) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverSide.Unmarshal(m, b)
}
func (m *DriverSide) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverSide.Marshal(b, m, deterministic)
}
func (dst *DriverSide) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverSide.Merge(dst, src)
}
func (m *DriverSide) XXX_Size() int {
	return xxx_messageInfo_DriverSide.Size(m)
}
func (m *DriverSide) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverSide.DiscardUnknown(m)
}

var xxx_messageInfo_DriverSide proto.InternalMessageInfo

type isDriverSide_Response interface {
	isDriverSide_Response()
}

type DriverSide_RegisterResp struct {
	RegisterResp *DriverSideRegisterationResp `protobuf:"bytes,3,opt,name=registerResp,oneof"`
}
type DriverSide_Createresponse struct {
	Createresponse *DriverSideCreateResp `protobuf:"bytes,4,opt,name=createresponse,oneof"`
}
type DriverSide_Deleteresponse struct {
	Deleteresponse *DriverSideDeleteResp `protobuf:"bytes,5,opt,name=deleteresponse,oneof"`
}
type DriverSide_Listresponse struct {
	Listresponse *DriverSideListResp `protobuf:"bytes,6,opt,name=listresponse,oneof"`
}

func (*DriverSide_RegisterResp) isDriverSide_Response()   {}
func (*DriverSide_Createresponse) isDriverSide_Response() {}
func (*DriverSide_Deleteresponse) isDriverSide_Response() {}
func (*DriverSide_Listresponse) isDriverSide_Response()   {}

func (m *DriverSide) GetResponse() isDriverSide_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *DriverSide) GetOperationID() int32 {
	if m != nil {
		return m.OperationID
	}
	return 0
}

func (m *DriverSide) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *DriverSide) GetRegisterResp() *DriverSideRegisterationResp {
	if x, ok := m.GetResponse().(*DriverSide_RegisterResp); ok {
		return x.RegisterResp
	}
	return nil
}

func (m *DriverSide) GetCreateresponse() *DriverSideCreateResp {
	if x, ok := m.GetResponse().(*DriverSide_Createresponse); ok {
		return x.Createresponse
	}
	return nil
}

func (m *DriverSide) GetDeleteresponse() *DriverSideDeleteResp {
	if x, ok := m.GetResponse().(*DriverSide_Deleteresponse); ok {
		return x.Deleteresponse
	}
	return nil
}

func (m *DriverSide) GetListresponse() *DriverSideListResp {
	if x, ok := m.GetResponse().(*DriverSide_Listresponse); ok {
		return x.Listresponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DriverSide) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DriverSide_OneofMarshaler, _DriverSide_OneofUnmarshaler, _DriverSide_OneofSizer, []interface{}{
		(*DriverSide_RegisterResp)(nil),
		(*DriverSide_Createresponse)(nil),
		(*DriverSide_Deleteresponse)(nil),
		(*DriverSide_Listresponse)(nil),
	}
}

func _DriverSide_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DriverSide)
	// response
	switch x := m.Response.(type) {
	case *DriverSide_RegisterResp:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RegisterResp); err != nil {
			return err
		}
	case *DriverSide_Createresponse:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Createresponse); err != nil {
			return err
		}
	case *DriverSide_Deleteresponse:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Deleteresponse); err != nil {
			return err
		}
	case *DriverSide_Listresponse:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Listresponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DriverSide.Response has unexpected type %T", x)
	}
	return nil
}

func _DriverSide_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DriverSide)
	switch tag {
	case 3: // response.registerResp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DriverSideRegisterationResp)
		err := b.DecodeMessage(msg)
		m.Response = &DriverSide_RegisterResp{msg}
		return true, err
	case 4: // response.createresponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DriverSideCreateResp)
		err := b.DecodeMessage(msg)
		m.Response = &DriverSide_Createresponse{msg}
		return true, err
	case 5: // response.deleteresponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DriverSideDeleteResp)
		err := b.DecodeMessage(msg)
		m.Response = &DriverSide_Deleteresponse{msg}
		return true, err
	case 6: // response.listresponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DriverSideListResp)
		err := b.DecodeMessage(msg)
		m.Response = &DriverSide_Listresponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DriverSide_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DriverSide)
	// response
	switch x := m.Response.(type) {
	case *DriverSide_RegisterResp:
		s := proto.Size(x.RegisterResp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DriverSide_Createresponse:
		s := proto.Size(x.Createresponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DriverSide_Deleteresponse:
		s := proto.Size(x.Deleteresponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DriverSide_Listresponse:
		s := proto.Size(x.Listresponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DriverSideRegisterationResp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverSideRegisterationResp) Reset()         { *m = DriverSideRegisterationResp{} }
func (m *DriverSideRegisterationResp) String() string { return proto.CompactTextString(m) }
func (*DriverSideRegisterationResp) ProtoMessage()    {}
func (*DriverSideRegisterationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{0, 0}
}
func (m *DriverSideRegisterationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverSideRegisterationResp.Unmarshal(m, b)
}
func (m *DriverSideRegisterationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverSideRegisterationResp.Marshal(b, m, deterministic)
}
func (dst *DriverSideRegisterationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverSideRegisterationResp.Merge(dst, src)
}
func (m *DriverSideRegisterationResp) XXX_Size() int {
	return xxx_messageInfo_DriverSideRegisterationResp.Size(m)
}
func (m *DriverSideRegisterationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverSideRegisterationResp.DiscardUnknown(m)
}

var xxx_messageInfo_DriverSideRegisterationResp proto.InternalMessageInfo

func (m *DriverSideRegisterationResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DriverSideRegisterationResp) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *DriverSideRegisterationResp) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *DriverSideRegisterationResp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type DriverSideCreateResp struct {
	ProviderID           string   `protobuf:"bytes,1,opt,name=providerID" json:"providerID,omitempty"`
	Nodename             string   `protobuf:"bytes,2,opt,name=nodename" json:"nodename,omitempty"`
	Error                int32    `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverSideCreateResp) Reset()         { *m = DriverSideCreateResp{} }
func (m *DriverSideCreateResp) String() string { return proto.CompactTextString(m) }
func (*DriverSideCreateResp) ProtoMessage()    {}
func (*DriverSideCreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{0, 1}
}
func (m *DriverSideCreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverSideCreateResp.Unmarshal(m, b)
}
func (m *DriverSideCreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverSideCreateResp.Marshal(b, m, deterministic)
}
func (dst *DriverSideCreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverSideCreateResp.Merge(dst, src)
}
func (m *DriverSideCreateResp) XXX_Size() int {
	return xxx_messageInfo_DriverSideCreateResp.Size(m)
}
func (m *DriverSideCreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverSideCreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_DriverSideCreateResp proto.InternalMessageInfo

func (m *DriverSideCreateResp) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *DriverSideCreateResp) GetNodename() string {
	if m != nil {
		return m.Nodename
	}
	return ""
}

func (m *DriverSideCreateResp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type DriverSideDeleteResp struct {
	Error                int32    `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverSideDeleteResp) Reset()         { *m = DriverSideDeleteResp{} }
func (m *DriverSideDeleteResp) String() string { return proto.CompactTextString(m) }
func (*DriverSideDeleteResp) ProtoMessage()    {}
func (*DriverSideDeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{0, 2}
}
func (m *DriverSideDeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverSideDeleteResp.Unmarshal(m, b)
}
func (m *DriverSideDeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverSideDeleteResp.Marshal(b, m, deterministic)
}
func (dst *DriverSideDeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverSideDeleteResp.Merge(dst, src)
}
func (m *DriverSideDeleteResp) XXX_Size() int {
	return xxx_messageInfo_DriverSideDeleteResp.Size(m)
}
func (m *DriverSideDeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverSideDeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DriverSideDeleteResp proto.InternalMessageInfo

func (m *DriverSideDeleteResp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type DriverSideListResp struct {
	List                 []string `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverSideListResp) Reset()         { *m = DriverSideListResp{} }
func (m *DriverSideListResp) String() string { return proto.CompactTextString(m) }
func (*DriverSideListResp) ProtoMessage()    {}
func (*DriverSideListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{0, 3}
}
func (m *DriverSideListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverSideListResp.Unmarshal(m, b)
}
func (m *DriverSideListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverSideListResp.Marshal(b, m, deterministic)
}
func (dst *DriverSideListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverSideListResp.Merge(dst, src)
}
func (m *DriverSideListResp) XXX_Size() int {
	return xxx_messageInfo_DriverSideListResp.Size(m)
}
func (m *DriverSideListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverSideListResp.DiscardUnknown(m)
}

var xxx_messageInfo_DriverSideListResp proto.InternalMessageInfo

func (m *DriverSideListResp) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *DriverSideListResp) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

// The message containing the MCM side structures
type MCMside struct {
	// operationID to match response with asynchronous requests
	OperationID int32 `protobuf:"varint,1,opt,name=operationID" json:"operationID,omitempty"`
	// operationType can be register, create, delete, getVMs
	OperationType        string                  `protobuf:"bytes,2,opt,name=operationType" json:"operationType,omitempty"`
	Operationparams      *MCMsideOperationParams `protobuf:"bytes,3,opt,name=operationparams" json:"operationparams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MCMside) Reset()         { *m = MCMside{} }
func (m *MCMside) String() string { return proto.CompactTextString(m) }
func (*MCMside) ProtoMessage()    {}
func (*MCMside) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{1}
}
func (m *MCMside) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MCMside.Unmarshal(m, b)
}
func (m *MCMside) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MCMside.Marshal(b, m, deterministic)
}
func (dst *MCMside) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MCMside.Merge(dst, src)
}
func (m *MCMside) XXX_Size() int {
	return xxx_messageInfo_MCMside.Size(m)
}
func (m *MCMside) XXX_DiscardUnknown() {
	xxx_messageInfo_MCMside.DiscardUnknown(m)
}

var xxx_messageInfo_MCMside proto.InternalMessageInfo

func (m *MCMside) GetOperationID() int32 {
	if m != nil {
		return m.OperationID
	}
	return 0
}

func (m *MCMside) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *MCMside) GetOperationparams() *MCMsideOperationParams {
	if m != nil {
		return m.Operationparams
	}
	return nil
}

type MCMsideMachineClassMeta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Revision             int32    `protobuf:"varint,2,opt,name=revision" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MCMsideMachineClassMeta) Reset()         { *m = MCMsideMachineClassMeta{} }
func (m *MCMsideMachineClassMeta) String() string { return proto.CompactTextString(m) }
func (*MCMsideMachineClassMeta) ProtoMessage()    {}
func (*MCMsideMachineClassMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{1, 0}
}
func (m *MCMsideMachineClassMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MCMsideMachineClassMeta.Unmarshal(m, b)
}
func (m *MCMsideMachineClassMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MCMsideMachineClassMeta.Marshal(b, m, deterministic)
}
func (dst *MCMsideMachineClassMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MCMsideMachineClassMeta.Merge(dst, src)
}
func (m *MCMsideMachineClassMeta) XXX_Size() int {
	return xxx_messageInfo_MCMsideMachineClassMeta.Size(m)
}
func (m *MCMsideMachineClassMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MCMsideMachineClassMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MCMsideMachineClassMeta proto.InternalMessageInfo

func (m *MCMsideMachineClassMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MCMsideMachineClassMeta) GetRevision() int32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

type MCMsideOperationParams struct {
	MachineClassMetaData *MCMsideMachineClassMeta `protobuf:"bytes,1,opt,name=machineClassMetaData" json:"machineClassMetaData,omitempty"`
	// cloudConfig has the secrets (username/password info to connect to provider account)
	CloudConfig          string   `protobuf:"bytes,2,opt,name=cloudConfig" json:"cloudConfig,omitempty"`
	UserData             string   `protobuf:"bytes,3,opt,name=userData" json:"userData,omitempty"`
	MachineID            string   `protobuf:"bytes,4,opt,name=machineID" json:"machineID,omitempty"`
	MachineName          string   `protobuf:"bytes,5,opt,name=machineName" json:"machineName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MCMsideOperationParams) Reset()         { *m = MCMsideOperationParams{} }
func (m *MCMsideOperationParams) String() string { return proto.CompactTextString(m) }
func (*MCMsideOperationParams) ProtoMessage()    {}
func (*MCMsideOperationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{1, 1}
}
func (m *MCMsideOperationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MCMsideOperationParams.Unmarshal(m, b)
}
func (m *MCMsideOperationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MCMsideOperationParams.Marshal(b, m, deterministic)
}
func (dst *MCMsideOperationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MCMsideOperationParams.Merge(dst, src)
}
func (m *MCMsideOperationParams) XXX_Size() int {
	return xxx_messageInfo_MCMsideOperationParams.Size(m)
}
func (m *MCMsideOperationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MCMsideOperationParams.DiscardUnknown(m)
}

var xxx_messageInfo_MCMsideOperationParams proto.InternalMessageInfo

func (m *MCMsideOperationParams) GetMachineClassMetaData() *MCMsideMachineClassMeta {
	if m != nil {
		return m.MachineClassMetaData
	}
	return nil
}

func (m *MCMsideOperationParams) GetCloudConfig() string {
	if m != nil {
		return m.CloudConfig
	}
	return ""
}

func (m *MCMsideOperationParams) GetUserData() string {
	if m != nil {
		return m.UserData
	}
	return ""
}

func (m *MCMsideOperationParams) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

func (m *MCMsideOperationParams) GetMachineName() string {
	if m != nil {
		return m.MachineName
	}
	return ""
}

// The request message containing metadata information
type Metadata struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{2}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// The response message containing error code and message
type ErrorResp struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResp) Reset()         { *m = ErrorResp{} }
func (m *ErrorResp) String() string { return proto.CompactTextString(m) }
func (*ErrorResp) ProtoMessage()    {}
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_infra_eec868e281ffaff7, []int{3}
}
func (m *ErrorResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResp.Unmarshal(m, b)
}
func (m *ErrorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResp.Marshal(b, m, deterministic)
}
func (dst *ErrorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResp.Merge(dst, src)
}
func (m *ErrorResp) XXX_Size() int {
	return xxx_messageInfo_ErrorResp.Size(m)
}
func (m *ErrorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResp.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResp proto.InternalMessageInfo

func (m *ErrorResp) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *ErrorResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DriverSide)(nil), "infra.DriverSide")
	proto.RegisterType((*DriverSideRegisterationResp)(nil), "infra.DriverSide.registerationResp")
	proto.RegisterType((*DriverSideCreateResp)(nil), "infra.DriverSide.createResp")
	proto.RegisterType((*DriverSideDeleteResp)(nil), "infra.DriverSide.deleteResp")
	proto.RegisterType((*DriverSideListResp)(nil), "infra.DriverSide.listResp")
	proto.RegisterType((*MCMside)(nil), "infra.MCMside")
	proto.RegisterType((*MCMsideMachineClassMeta)(nil), "infra.MCMside.machineClassMeta")
	proto.RegisterType((*MCMsideOperationParams)(nil), "infra.MCMside.operationParams")
	proto.RegisterType((*Metadata)(nil), "infra.Metadata")
	proto.RegisterType((*ErrorResp)(nil), "infra.ErrorResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InfragrpcClient is the client API for Infragrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfragrpcClient interface {
	// infra operations
	Register(ctx context.Context, opts ...grpc.CallOption) (Infragrpc_RegisterClient, error)
	// Share Metadata
	ShareMeta(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*ErrorResp, error)
}

type infragrpcClient struct {
	cc *grpc.ClientConn
}

func NewInfragrpcClient(cc *grpc.ClientConn) InfragrpcClient {
	return &infragrpcClient{cc}
}

func (c *infragrpcClient) Register(ctx context.Context, opts ...grpc.CallOption) (Infragrpc_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Infragrpc_serviceDesc.Streams[0], "/infra.Infragrpc/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &infragrpcRegisterClient{stream}
	return x, nil
}

type Infragrpc_RegisterClient interface {
	Send(*DriverSide) error
	Recv() (*MCMside, error)
	grpc.ClientStream
}

type infragrpcRegisterClient struct {
	grpc.ClientStream
}

func (x *infragrpcRegisterClient) Send(m *DriverSide) error {
	return x.ClientStream.SendMsg(m)
}

func (x *infragrpcRegisterClient) Recv() (*MCMside, error) {
	m := new(MCMside)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *infragrpcClient) ShareMeta(ctx context.Context, in *Metadata, opts ...grpc.CallOption) (*ErrorResp, error) {
	out := new(ErrorResp)
	err := c.cc.Invoke(ctx, "/infra.Infragrpc/ShareMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfragrpcServer is the server API for Infragrpc service.
type InfragrpcServer interface {
	// infra operations
	Register(Infragrpc_RegisterServer) error
	// Share Metadata
	ShareMeta(context.Context, *Metadata) (*ErrorResp, error)
}

func RegisterInfragrpcServer(s *grpc.Server, srv InfragrpcServer) {
	s.RegisterService(&_Infragrpc_serviceDesc, srv)
}

func _Infragrpc_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InfragrpcServer).Register(&infragrpcRegisterServer{stream})
}

type Infragrpc_RegisterServer interface {
	Send(*MCMside) error
	Recv() (*DriverSide, error)
	grpc.ServerStream
}

type infragrpcRegisterServer struct {
	grpc.ServerStream
}

func (x *infragrpcRegisterServer) Send(m *MCMside) error {
	return x.ServerStream.SendMsg(m)
}

func (x *infragrpcRegisterServer) Recv() (*DriverSide, error) {
	m := new(DriverSide)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Infragrpc_ShareMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfragrpcServer).ShareMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.Infragrpc/ShareMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfragrpcServer).ShareMeta(ctx, req.(*Metadata))
	}
	return interceptor(ctx, in, info, handler)
}

var _Infragrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infra.Infragrpc",
	HandlerType: (*InfragrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShareMeta",
			Handler:    _Infragrpc_ShareMeta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Infragrpc_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "infra.proto",
}

func init() { proto.RegisterFile("infra.proto", fileDescriptor_infra_eec868e281ffaff7) }

var fileDescriptor_infra_eec868e281ffaff7 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0x8e, 0x03, 0x4e, 0xf0, 0x90, 0x26, 0x64, 0x95, 0x83, 0x65, 0x45, 0x29, 0x72, 0x7b, 0xe0,
	0x84, 0x22, 0x52, 0xa9, 0xd7, 0x2a, 0xd0, 0x28, 0x1c, 0xa8, 0xaa, 0xa5, 0xe7, 0x4a, 0x5b, 0x3c,
	0x21, 0xab, 0x80, 0xd7, 0x9a, 0x35, 0x48, 0x7d, 0x9f, 0x3e, 0x4b, 0x9f, 0xa4, 0x0f, 0x52, 0xed,
	0x7a, 0xfd, 0x03, 0xa4, 0xb7, 0xde, 0x66, 0x46, 0xdf, 0x7c, 0xfb, 0xcd, 0x37, 0x63, 0x43, 0x57,
	0xa6, 0x4f, 0x24, 0x86, 0x19, 0xa9, 0x5c, 0x31, 0xdf, 0x26, 0xf1, 0x2f, 0x1f, 0x60, 0x42, 0x72,
	0x8b, 0x34, 0x97, 0x09, 0xb2, 0x3e, 0x74, 0x55, 0x86, 0x24, 0x72, 0xa9, 0xd2, 0xe9, 0x24, 0xf4,
	0xfa, 0xde, 0xc0, 0xe7, 0xcd, 0x12, 0x7b, 0x0f, 0x6f, 0xaa, 0xf4, 0xdb, 0xcf, 0x0c, 0xc3, 0xe3,
	0xbe, 0x37, 0x08, 0xf8, 0x6e, 0x91, 0x4d, 0xe1, 0x8c, 0x70, 0x29, 0x75, 0x8e, 0xc4, 0x51, 0x67,
	0x61, 0xab, 0xef, 0x0d, 0xba, 0xa3, 0x77, 0xc3, 0x42, 0x41, 0xfd, 0xe0, 0xb0, 0x44, 0xd9, 0x56,
	0x03, 0x7d, 0x3c, 0xe2, 0x3b, 0xad, 0xec, 0x01, 0xce, 0x17, 0x84, 0x22, 0x47, 0x42, 0x9d, 0xa9,
	0x54, 0x63, 0xd8, 0xb6, 0x64, 0xd7, 0x87, 0x64, 0x05, 0xce, 0xb1, 0xec, 0x75, 0x19, 0x9e, 0x04,
	0x57, 0xd8, 0xe0, 0xf1, 0xff, 0xc5, 0x53, 0xe0, 0x4a, 0x9e, 0xdd, 0x2e, 0xf6, 0x09, 0xce, 0x56,
	0x52, 0xe7, 0x15, 0xcb, 0x89, 0x65, 0x89, 0x0e, 0x59, 0x0c, 0xaa, 0x9c, 0xa8, 0xd9, 0x11, 0xbd,
	0xc0, 0xe5, 0xc1, 0xd8, 0x8c, 0x41, 0x3b, 0x15, 0x6b, 0xb4, 0x96, 0x07, 0xdc, 0xc6, 0xec, 0x0a,
	0xfc, 0x25, 0xa9, 0x4d, 0xe6, 0x3c, 0x2e, 0x12, 0x83, 0x7c, 0x91, 0x69, 0x62, 0x3d, 0x0d, 0xb8,
	0x8d, 0x59, 0x08, 0xa7, 0x5b, 0x24, 0x2d, 0x55, 0x6a, 0xdd, 0x09, 0x78, 0x99, 0x46, 0xdf, 0x01,
	0x6a, 0x5b, 0xd8, 0x0d, 0x40, 0x46, 0x6a, 0x2b, 0x13, 0x24, 0xb7, 0xde, 0x80, 0x37, 0x2a, 0x2c,
	0x82, 0x4e, 0xaa, 0x12, 0xb4, 0x4a, 0x8a, 0x47, 0xab, 0xdc, 0xa8, 0x41, 0x22, 0x45, 0xf6, 0x61,
	0x9f, 0x17, 0x49, 0x14, 0x03, 0xd4, 0x76, 0xd5, 0x18, 0xaf, 0x89, 0xf9, 0x00, 0x9d, 0xd2, 0x0c,
	0xa3, 0xde, 0xc4, 0xa1, 0xd7, 0x6f, 0x19, 0xf5, 0x26, 0xae, 0xbb, 0x8e, 0x1b, 0x5d, 0xf7, 0x00,
	0x9d, 0xd2, 0xb2, 0xf8, 0x77, 0x0b, 0x4e, 0x67, 0xe3, 0x99, 0xfe, 0x9f, 0x37, 0xfa, 0x08, 0x17,
	0x55, 0x21, 0x13, 0x24, 0xd6, 0xda, 0x9d, 0xe9, 0x8d, 0xdb, 0xa5, 0x7b, 0x70, 0x58, 0xa1, 0xbe,
	0x5a, 0x14, 0xdf, 0x6f, 0x8b, 0xee, 0xa1, 0xb7, 0x16, 0x8b, 0x67, 0x99, 0xe2, 0x78, 0x25, 0xb4,
	0x9e, 0x61, 0x2e, 0x5e, 0xdd, 0x67, 0x64, 0x26, 0xda, 0x4a, 0xbb, 0xa6, 0x62, 0xd4, 0x2a, 0x8f,
	0xfe, 0x78, 0x0d, 0x39, 0xc5, 0x43, 0x6c, 0x0e, 0x57, 0xfb, 0xbc, 0x13, 0x91, 0x0b, 0xcb, 0xd9,
	0x1d, 0xbd, 0xdd, 0x93, 0xb9, 0x0f, 0xe5, 0xaf, 0x36, 0x1b, 0xfb, 0x16, 0x2b, 0xb5, 0x49, 0xc6,
	0x2a, 0x7d, 0x92, 0x4b, 0x67, 0x4d, 0xb3, 0x64, 0x64, 0x6e, 0x34, 0x92, 0x7d, 0xaa, 0x38, 0xb2,
	0x2a, 0x67, 0xd7, 0x10, 0x38, 0xd6, 0xe9, 0xc4, 0x9d, 0x5a, 0x5d, 0x30, 0xdc, 0x2e, 0xf9, 0x62,
	0x66, 0xf7, 0x0b, 0xee, 0x46, 0x29, 0x7e, 0x80, 0x8e, 0x51, 0x92, 0x88, 0xc2, 0xa2, 0xdc, 0x6c,
	0xc7, 0x59, 0x64, 0xe2, 0xca, 0xb6, 0xe3, 0x86, 0x6d, 0x0c, 0xda, 0x49, 0xad, 0xc5, 0xc6, 0xf1,
	0x47, 0x08, 0x3e, 0x9b, 0x2b, 0xb1, 0x37, 0xd5, 0x83, 0x16, 0x52, 0x79, 0x73, 0x26, 0x34, 0xdf,
	0xc3, 0x1a, 0xb5, 0x16, 0xcb, 0x92, 0xa9, 0x4c, 0x47, 0x04, 0xc1, 0xd4, 0xd8, 0xb6, 0xa4, 0x6c,
	0xc1, 0xee, 0xa0, 0xc3, 0xdd, 0x97, 0xc8, 0x2e, 0x0f, 0xbe, 0xe0, 0xe8, 0x7c, 0xd7, 0xe1, 0xf8,
	0x68, 0xe0, 0xdd, 0x7a, 0xec, 0x16, 0x82, 0xf9, 0xb3, 0x20, 0xb4, 0x6b, 0xbe, 0x28, 0x21, 0x6e,
	0xa8, 0xa8, 0xe7, 0x0a, 0x95, 0xba, 0xf8, 0xe8, 0xc7, 0x89, 0xfd, 0xe5, 0xde, 0xfd, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x0c, 0x1f, 0xaf, 0x88, 0x81, 0x05, 0x00, 0x00,
}
