// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/gardener/node-controller-manager/pkg/apis/machine/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AWSMachineClassLister helps list AWSMachineClasses.
type AWSMachineClassLister interface {
	// List lists all AWSMachineClasses in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.AWSMachineClass, err error)
	// Get retrieves the AWSMachineClass from the index for a given name.
	Get(name string) (*v1alpha1.AWSMachineClass, error)
	AWSMachineClassListerExpansion
}

// aWSMachineClassLister implements the AWSMachineClassLister interface.
type aWSMachineClassLister struct {
	indexer cache.Indexer
}

// NewAWSMachineClassLister returns a new AWSMachineClassLister.
func NewAWSMachineClassLister(indexer cache.Indexer) AWSMachineClassLister {
	return &aWSMachineClassLister{indexer: indexer}
}

// List lists all AWSMachineClasses in the indexer.
func (s *aWSMachineClassLister) List(selector labels.Selector) (ret []*v1alpha1.AWSMachineClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AWSMachineClass))
	})
	return ret, err
}

// Get retrieves the AWSMachineClass from the index for a given name.
func (s *aWSMachineClassLister) Get(name string) (*v1alpha1.AWSMachineClass, error) {
	key := &v1alpha1.AWSMachineClass{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("awsmachineclass"), name)
	}
	return obj.(*v1alpha1.AWSMachineClass), nil
}
