// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/gardener/node-controller-manager/pkg/apis/machine/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MachineLister helps list Machines.
type MachineLister interface {
	// List lists all Machines in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.Machine, err error)
	// Get retrieves the Machine from the index for a given name.
	Get(name string) (*v1alpha1.Machine, error)
	MachineListerExpansion
}

// machineLister implements the MachineLister interface.
type machineLister struct {
	indexer cache.Indexer
}

// NewMachineLister returns a new MachineLister.
func NewMachineLister(indexer cache.Indexer) MachineLister {
	return &machineLister{indexer: indexer}
}

// List lists all Machines in the indexer.
func (s *machineLister) List(selector labels.Selector) (ret []*v1alpha1.Machine, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Machine))
	})
	return ret, err
}

// Get retrieves the Machine from the index for a given name.
func (s *machineLister) Get(name string) (*v1alpha1.Machine, error) {
	key := &v1alpha1.Machine{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("machine"), name)
	}
	return obj.(*v1alpha1.Machine), nil
}
