// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MetalMachineClassLister helps list MetalMachineClasses.
type MetalMachineClassLister interface {
	// List lists all MetalMachineClasses in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.MetalMachineClass, err error)
	// MetalMachineClasses returns an object that can list and get MetalMachineClasses.
	MetalMachineClasses(namespace string) MetalMachineClassNamespaceLister
	MetalMachineClassListerExpansion
}

// metalMachineClassLister implements the MetalMachineClassLister interface.
type metalMachineClassLister struct {
	indexer cache.Indexer
}

// NewMetalMachineClassLister returns a new MetalMachineClassLister.
func NewMetalMachineClassLister(indexer cache.Indexer) MetalMachineClassLister {
	return &metalMachineClassLister{indexer: indexer}
}

// List lists all MetalMachineClasses in the indexer.
func (s *metalMachineClassLister) List(selector labels.Selector) (ret []*v1alpha1.MetalMachineClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MetalMachineClass))
	})
	return ret, err
}

// MetalMachineClasses returns an object that can list and get MetalMachineClasses.
func (s *metalMachineClassLister) MetalMachineClasses(namespace string) MetalMachineClassNamespaceLister {
	return metalMachineClassNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MetalMachineClassNamespaceLister helps list and get MetalMachineClasses.
type MetalMachineClassNamespaceLister interface {
	// List lists all MetalMachineClasses in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.MetalMachineClass, err error)
	// Get retrieves the MetalMachineClass from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.MetalMachineClass, error)
	MetalMachineClassNamespaceListerExpansion
}

// metalMachineClassNamespaceLister implements the MetalMachineClassNamespaceLister
// interface.
type metalMachineClassNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MetalMachineClasses in the indexer for a given namespace.
func (s metalMachineClassNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MetalMachineClass, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MetalMachineClass))
	})
	return ret, err
}

// Get retrieves the MetalMachineClass from the indexer for a given namespace and name.
func (s metalMachineClassNamespaceLister) Get(name string) (*v1alpha1.MetalMachineClass, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("metalmachineclass"), name)
	}
	return obj.(*v1alpha1.MetalMachineClass), nil
}
