// This file was automatically generated by lister-gen

package internalversion

import (
	node "github.com/gardener/node-controller-manager/pkg/apis/node"
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// InstanceLister helps list Instances.
type InstanceLister interface {
	// List lists all Instances in the indexer.
	List(selector labels.Selector) (ret []*node.Instance, err error)
	// Get retrieves the Instance from the index for a given name.
	Get(name string) (*node.Instance, error)
	InstanceListerExpansion
}

// instanceLister implements the InstanceLister interface.
type instanceLister struct {
	indexer cache.Indexer
}

// NewInstanceLister returns a new InstanceLister.
func NewInstanceLister(indexer cache.Indexer) InstanceLister {
	return &instanceLister{indexer: indexer}
}

// List lists all Instances in the indexer.
func (s *instanceLister) List(selector labels.Selector) (ret []*node.Instance, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*node.Instance))
	})
	return ret, err
}

// Get retrieves the Instance from the index for a given name.
func (s *instanceLister) Get(name string) (*node.Instance, error) {
	key := &node.Instance{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(node.Resource("instance"), name)
	}
	return obj.(*node.Instance), nil
}
