// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"github.com/gardener/machine-controller-manager/pkg/client/clientset/internalversion/scheme"
	rest "k8s.io/client-go/rest"
)

type ClusterInterface interface {
	RESTClient() rest.Interface
	ClustersGetter
	MachinesGetter
	MachineDeploymentsGetter
	MachineSetsGetter
}

// ClusterClient is used to interact with features provided by the cluster.k8s.io group.
type ClusterClient struct {
	restClient rest.Interface
}

func (c *ClusterClient) Clusters(namespace string) ClusterInterface {
	return newClusters(c, namespace)
}

func (c *ClusterClient) Machines(namespace string) MachineInterface {
	return newMachines(c, namespace)
}

func (c *ClusterClient) MachineDeployments(namespace string) MachineDeploymentInterface {
	return newMachineDeployments(c, namespace)
}

func (c *ClusterClient) MachineSets(namespace string) MachineSetInterface {
	return newMachineSets(c, namespace)
}

// NewForConfig creates a new ClusterClient for the given config.
func NewForConfig(c *rest.Config) (*ClusterClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ClusterClient{client}, nil
}

// NewForConfigOrDie creates a new ClusterClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ClusterClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ClusterClient for the given RESTClient.
func New(c rest.Interface) *ClusterClient {
	return &ClusterClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	g, err := scheme.Registry.Group("cluster.k8s.io")
	if err != nil {
		return err
	}

	config.APIPath = "/apis"
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	if config.GroupVersion == nil || config.GroupVersion.Group != g.GroupVersion.Group {
		gv := g.GroupVersion
		config.GroupVersion = &gv
	}
	config.NegotiatedSerializer = scheme.Codecs

	if config.QPS == 0 {
		config.QPS = 5
	}
	if config.Burst == 0 {
		config.Burst = 10
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ClusterClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
