# Sample secret

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # Aliyun cloud config file (base64 encoded)
  aliyunAccessKeyId: "aliyun-access-key-id" # Aliyun access key id (base64 encoded)
  aliyunAccessKeySecret: "aliyun-access-key-secret" # Aliyun secret access key (base64 encoded)
type: Opaque
