# Sample Azure machine class

apiVersion: machine.sapcloud.io/v1alpha1
kind: AzureMachineClass
metadata:
  name: test-azure # Name of aws machine class goes here
spec:
  location: "westamerica" # Region in which machine is to be deployed
  resourceGroup: "sample-resource-group"
  subnetInfo:
    vnetName: "sample-vnet"
    subnetName: "sample-subnet-in-given-vnet"
  secretRef:
    name: "test-secret"
    namespace: "default"
  tags:
    "tag1": "key1"
    "tag2": "key2"
  properties:
    hardwareProfile:
      vmSize: "Standard_DS1_V2" # VMsize based on azure machine kinds
    storageProfile:
      imageReference: # Details about the image to be used
        publisher: "CoreOS" 
        offer: "CoreOS"
        sku: "Beta"
        version: "sample-image-version"
      osDisk: 
        caching: "None" # Caching Strategy
        diskSizeGB: 50 # Size of Disk
        createOption: "FromImage" # Create option for disk
    osProfile: 
      adminUserName: "core" # Admin user name
      linuxConfiguration:
        disablePasswordAuthentication: true # Password authentication
        ssh:
          publicKeys:
            path: "/path/to/public-key/in/machine" # Path to public key
            keyData: "public-key"
    availabilitySet:
      id: "/subscriptions/subscription-id/resourceGroups/resource-group-name/providers/Microsoft.Compute/availabilitySets/availablity-set-name"
