# Sample AWS machine class

apiVersion: machine.sapcloud.io/v1alpha1
kind: OpenStackMachineClass
metadata:
  name: test-openstack # Name of aws machine class goes here
spec:
  flavorName: <flavor_name> 
  keyName: <keypair_name> 
  imageName: <image_name>
  networkID: <network_id>
  securityGroups:
  - <security_group_name>
  region: <region>
  availabilityZone: <availability_zone>
  tags:
    Name: sample-machine-name # Name tag that can be used to identify a machine at AWS
    kubernetes.io/cluster/cluster-name: "1" # Tag that helps a new node to join existing AWS cluster (replace cluster-name with real cluster name)
    tag1: tag1-value # A set of additional tags attached to a machine (optional)
    tag2: tag2-value # A set of additional tags attached to a machine (optional)
  secretRef: # Secret pointing to a secret which contains the provider secret and cloudconfig
    namespace: default  # Namespace
    name: test-secret # Name of the secret


