// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AWSMachineClassExpansion interface{}

type AliyunMachineClassExpansion interface{}

type AzureMachineClassExpansion interface{}

type GCPMachineClassExpansion interface{}

type MachineExpansion interface{}

type MachineDeploymentExpansion interface{}

type MachineSetExpansion interface{}

type MachineTemplateExpansion interface{}

type OpenStackMachineClassExpansion interface{}

type ScaleExpansion interface{}
