# Sample machine object

apiVersion: machine.sapcloud.io/v1alpha1
kind: Machine
metadata:
  name: test-machine # Name of the machine to be created
  namespace: aws
  labels:
    test-label: test-label # Label used by machine-set to match (optional)
spec:
  class:
    kind: AWSMachineClass # Machine class template used to create machine, could be AWS/GCP/Azure/Other-cloud-providers
    name: mc-v1 # Name of the machine class
