package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	gardenerauthv1alpha1 "github.com/gardener/gardener/pkg/apis/authentication/v1alpha1"
	gardenercorev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	"github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
	"github.com/gardener/machine-controller-manager/pkg/client/clientset/versioned/scheme"
	"github.com/spf13/cobra"
	appsv1 "k8s.io/api/apps/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	kjson "k8s.io/apimachinery/pkg/runtime/serializer/json"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type CopyShootFlags struct {
	Landscape string
	Project   string
	Shoot     string
	// FetchConfig is the flag to download cluster mcm/provider config
	// from actual cluster with fallback to defaults generated by setup
	FetchConfig bool
}

var (
	copyShootFlags          CopyShootFlags
	landscapeKubeconfigPath string
)

var copyShootCmd = &cobra.Command{
	Use:                   "copyshoot {--clusters name} {-l landscape} {-p project} {-s shoot} [-f true|false]",
	Short:                 "Fetches MachineDeployments and MachineClasses from specified shoot.",
	DisableFlagsInUseLine: true,
	PreRunE: func(cmd *cobra.Command, _ []string) (err error) {
		// CopyShoot only works with one cluster at a time, to ensure user doesn't
		// pass incorrect project when specifying multiple clusters. Multiple invocations
		// are to be made in case data for multiple clusters needs to be fetched.
		clusterNames := getClusterNames(cmd)
		if len(clusterNames) > 1 {
			return fmt.Errorf("more than one cluster name specified")
		}

		if copyShootFlags.Landscape == "" ||
			copyShootFlags.Project == "" ||
			copyShootFlags.Shoot == "" {
			return fmt.Errorf("required flags not passed")
		}

		clustersDir := getClustersDir(cmd)
		err = prepareClusterDirs(clustersDir, clusterNames)
		if err != nil {
			return err
		}
		// Since this command fetches the MachineDeployment and the MachineClass objects,
		// it requires the proper oidc permissions for the user to be present i.e. they
		// should have control plane access.
		return checkLandscapeKubeconfigPresent(copyShootFlags.Landscape)
	},
	RunE: func(cmd *cobra.Command, _ []string) (err error) {
		cmd.SilenceUsage = true

		ctx := cmd.Context()
		scheme := scheme.Scheme

		seedClient, err := getSeedClient(ctx, scheme, landscapeKubeconfigPath, copyShootFlags)
		if err != nil {
			return
		}

		var (
			mccList        v1alpha1.MachineClassList
			mcdList        v1alpha1.MachineDeploymentList
			shootNamespace = fmt.Sprintf(
				"shoot--%s--%s", copyShootFlags.Project, copyShootFlags.Shoot,
			)
		)
		err = seedClient.List(ctx, &mccList, &client.ListOptions{
			Namespace: shootNamespace,
		})
		if err != nil {
			return
		}
		err = seedClient.List(ctx, &mcdList, &client.ListOptions{
			Namespace: shootNamespace,
		})
		if err != nil {
			return
		}

		for _, clusterName := range getClusterNames(cmd) {
			clusterPath := filepath.Join(getClustersDir(cmd), clusterName)
			mccFilePath := filepath.Join(clusterPath, fileNameMachineClass)
			mcdFilePath := filepath.Join(clusterPath, fileNameMachineDeployment)

			fmt.Printf("Saving MachineClass list to %q\n", mccFilePath)
			err = saveObject(&mccList, mccFilePath, scheme)
			if err != nil {
				return
			}
			fmt.Printf("Saving MachineDeployment list to %q\n", mcdFilePath)
			err = saveObject(&mcdList, mcdFilePath, scheme)
			if err != nil {
				return
			}
		}

		// Already validated that there will only be a single cluster name passed
		clusterPath := filepath.Join(getClustersDir(cmd), getClusterNames(cmd)[0])

		if !copyShootFlags.FetchConfig {
			// Use default flags for setting up MCM and MC, also append the namespace flag
			return generateStartConfigs(clusterPath, defaultMCMFlags, defaultMCFlags, true)
		}
		// Fetch the MCM deployment from the cluster and get the MCM and the provider
		// container flags
		mcmArgs, mcArgs, err := getClusterComponentFlags(ctx, seedClient, shootNamespace)
		if err != nil {
			return
		}
		// No need to append the namespace flag, it would already be present
		return generateStartConfigs(clusterPath, mcmArgs, mcArgs, false)
	},
}

func init() {
	copyShootCmd.Flags().StringVarP(
		&copyShootFlags.Landscape, "landscape", "l", "",
		"gardener landscape name (required)",
	)
	_ = copyShootCmd.MarkFlagRequired("landscape")

	copyShootCmd.Flags().StringVarP(
		&copyShootFlags.Project, "project", "p", "",
		"gardener project name (required)",
	)
	_ = copyShootCmd.MarkFlagRequired("project")

	copyShootCmd.Flags().StringVarP(
		&copyShootFlags.Shoot, "shoot", "s", "",
		"gardener shoot name (required)",
	)
	_ = copyShootCmd.MarkFlagRequired("shoot")

	copyShootCmd.Flags().BoolVarP(
		&copyShootFlags.FetchConfig, "fetch-config", "f", true,
		"fetch component configuration from cluster",
	)
}

func getSeedClient(
	ctx context.Context,
	scheme *runtime.Scheme,
	landscapeKubeconfigPath string,
	flags CopyShootFlags,
) (client.Client, error) {
	err := registerSchemes(scheme)
	if err != nil {
		return nil, err
	}
	landscapeClient, err := createClient(landscapeKubeconfigPath, scheme)
	if err != nil {
		return nil, err
	}

	shoot, err := getShootObject(ctx, landscapeClient, flags)
	if err != nil {
		return nil, err
	}
	seedName := ptr.Deref(shoot.Spec.SeedName, "")
	if seedName == "" {
		return nil, fmt.Errorf("shoot %q has empty seedname", flags.Shoot)
	}

	seedViewerKubeconfigPath, err := getViewerKubeconfig(ctx, landscapeClient, seedName)
	if err != nil {
		return nil, err
	}
	return createClient(seedViewerKubeconfigPath, scheme)
}

func checkLandscapeKubeconfigPresent(landscape string) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	trimmedLandscape := strings.TrimPrefix(landscape, "sap-landscape-")
	landscapeKubeconfigPath = filepath.Join(
		homeDir, ".garden", "landscapes", trimmedLandscape, "oidc-kubeconfig.yaml",
	)

	_, err = os.Stat(landscapeKubeconfigPath)
	if err != nil {
		return fmt.Errorf("cannot find kubeconfig for landscape %q: %w", landscape, err)
	}
	return nil
}

func registerSchemes(clientScheme *runtime.Scheme) error {
	if err := appsv1.AddToScheme(clientScheme); err != nil {
		return fmt.Errorf("failed to add appsv1 scheme: %w", err)
	}
	if err := gardenercorev1beta1.AddToScheme(clientScheme); err != nil {
		return fmt.Errorf("failed to add gardener core scheme: %w", err)
	}
	if err := gardenerauthv1alpha1.AddToScheme(clientScheme); err != nil {
		return fmt.Errorf("failed to add gardener auth scheme: %w", err)
	}
	return nil
}

func createClient(kubeconfig string, scheme *runtime.Scheme) (client.Client, error) {
	restCfg, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
	if err != nil {
		return nil, fmt.Errorf("failed to create rest.Config from %q: %w", kubeconfig, err)
	}
	return client.New(restCfg, client.Options{Scheme: scheme})
}

func getShootObject(
	ctx context.Context,
	landscapeClient client.Client,
	flags CopyShootFlags,
) (shoot gardenercorev1beta1.Shoot, err error) {
	key := client.ObjectKey{
		Namespace: "garden-" + flags.Project,
		Name:      flags.Shoot,
	}

	if err = landscapeClient.Get(ctx, key, &shoot); err != nil {
		err = fmt.Errorf("error fetching the shoot object: %w", err)
		return
	}
	return
}

func getViewerKubeconfig(
	ctx context.Context,
	landscapeClient client.Client,
	seedName string,
) (string, error) {
	shoot := &gardenercorev1beta1.Shoot{
		ObjectMeta: metav1.ObjectMeta{
			Name:      seedName,
			Namespace: "garden",
		},
	}
	request := &gardenerauthv1alpha1.ViewerKubeconfigRequest{
		Spec: gardenerauthv1alpha1.ViewerKubeconfigRequestSpec{
			ExpirationSeconds: ptr.To[int64](600),
		},
	}

	err := landscapeClient.SubResource("viewerkubeconfig").Create(ctx, shoot, request)
	if err != nil {
		return "", fmt.Errorf("could not create viewerkubeconfig request: %w", err)
	}

	if len(request.Status.Kubeconfig) == 0 {
		return "", fmt.Errorf("kubeconfig not found in ViewerKubeconfigRequest status")
	}

	kubeConfigFileName := seedName + "_viewer-kubeconfig.yaml"
	kubeConfigPath := filepath.Join(os.TempDir(), kubeConfigFileName)
	if err := os.WriteFile(kubeConfigPath, request.Status.Kubeconfig, 0600); err != nil {
		return "", err
	}
	fmt.Printf("Saving seed %q viewerkubeconfig\n", seedName)
	return kubeConfigPath, nil
}

func saveObject(obj runtime.Object, path string, scheme *runtime.Scheme) error {
	ser := kjson.NewSerializerWithOptions(
		kjson.DefaultMetaFactory, scheme, scheme, kjson.SerializerOptions{
			Yaml: true, Pretty: true,
		},
	)

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("failed to open file %q: %w", path, err)
	}
	defer f.Close()

	fmt.Printf("Saving %q\n", path)
	return ser.Encode(obj, f)
}

func getClusterComponentFlags(
	ctx context.Context,
	seedClient client.Client,
	shootNamespace string,
) (mcmArgs, mcArgs string, err error) {
	var (
		mcmDeployment appsv1.Deployment
		deploymentKey = client.ObjectKey{
			Name:      "machine-controller-manager",
			Namespace: shootNamespace,
		}
	)

	fmt.Printf(
		"Fetching %s cluster's machine-controller-manager deployment\n",
		copyShootFlags.Shoot,
	)
	err = seedClient.Get(ctx, deploymentKey, &mcmDeployment)
	if err != nil {
		return
	}
	mcmContainers := mcmDeployment.Spec.Template.Spec.Containers
	if len(mcmContainers) < 2 {
		err = fmt.Errorf(
			"%q deployment has unexpected containers length: %d",
			deploymentKey.Name, len(mcmContainers),
		)
		return
	}

	if strings.Contains(mcmContainers[0].Command[0], binaryNameMCM) {
		mcmArgs = modifyContainerArgs(mcmContainers[0].Command[1:])
		mcArgs = modifyContainerArgs(mcmContainers[1].Args[0:])
	} else {
		mcmArgs = modifyContainerArgs(mcmContainers[1].Command[1:])
		mcArgs = modifyContainerArgs(mcmContainers[0].Args[0:])
	}

	return mcmArgs, mcArgs, nil
}

func modifyContainerArgs(args []string) string {
	// Remove any flags related to kubeconfig
	// --kubeconfig, --control-kubeconfig, --target-kubeconfig
	// These don't point to the virtual cluster kubeconfig
	args = slices.DeleteFunc(args, func(arg string) bool {
		return strings.Contains(arg, "kubeconfig=")
	})

	return strings.Join(args, " ")
}
