// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "code.sapcloud.io/kubernetes/node-controller-manager/pkg/apis/node/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// InstanceSetLister helps list InstanceSets.
type InstanceSetLister interface {
	// List lists all InstanceSets in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.InstanceSet, err error)
	// Get retrieves the InstanceSet from the index for a given name.
	Get(name string) (*v1alpha1.InstanceSet, error)
	InstanceSetListerExpansion
}

// instanceSetLister implements the InstanceSetLister interface.
type instanceSetLister struct {
	indexer cache.Indexer
}

// NewInstanceSetLister returns a new InstanceSetLister.
func NewInstanceSetLister(indexer cache.Indexer) InstanceSetLister {
	return &instanceSetLister{indexer: indexer}
}

// List lists all InstanceSets in the indexer.
func (s *instanceSetLister) List(selector labels.Selector) (ret []*v1alpha1.InstanceSet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.InstanceSet))
	})
	return ret, err
}

// Get retrieves the InstanceSet from the index for a given name.
func (s *instanceSetLister) Get(name string) (*v1alpha1.InstanceSet, error) {
	key := &v1alpha1.InstanceSet{ObjectMeta: v1.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("instanceset"), name)
	}
	return obj.(*v1alpha1.InstanceSet), nil
}
