/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOpenStackMachineClasses implements OpenStackMachineClassInterface
type FakeOpenStackMachineClasses struct {
	Fake *FakeMachine
	ns   string
}

var openstackmachineclassesResource = schema.GroupVersionResource{Group: "machine.sapcloud.io", Version: "", Resource: "openstackmachineclasses"}

var openstackmachineclassesKind = schema.GroupVersionKind{Group: "machine.sapcloud.io", Version: "", Kind: "OpenStackMachineClass"}

// Get takes name of the openStackMachineClass, and returns the corresponding openStackMachineClass object, and an error if there is any.
func (c *FakeOpenStackMachineClasses) Get(name string, options v1.GetOptions) (result *machine.OpenStackMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(openstackmachineclassesResource, c.ns, name), &machine.OpenStackMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.OpenStackMachineClass), err
}

// List takes label and field selectors, and returns the list of OpenStackMachineClasses that match those selectors.
func (c *FakeOpenStackMachineClasses) List(opts v1.ListOptions) (result *machine.OpenStackMachineClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(openstackmachineclassesResource, openstackmachineclassesKind, c.ns, opts), &machine.OpenStackMachineClassList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &machine.OpenStackMachineClassList{ListMeta: obj.(*machine.OpenStackMachineClassList).ListMeta}
	for _, item := range obj.(*machine.OpenStackMachineClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested openStackMachineClasses.
func (c *FakeOpenStackMachineClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(openstackmachineclassesResource, c.ns, opts))

}

// Create takes the representation of a openStackMachineClass and creates it.  Returns the server's representation of the openStackMachineClass, and an error, if there is any.
func (c *FakeOpenStackMachineClasses) Create(openStackMachineClass *machine.OpenStackMachineClass) (result *machine.OpenStackMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(openstackmachineclassesResource, c.ns, openStackMachineClass), &machine.OpenStackMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.OpenStackMachineClass), err
}

// Update takes the representation of a openStackMachineClass and updates it. Returns the server's representation of the openStackMachineClass, and an error, if there is any.
func (c *FakeOpenStackMachineClasses) Update(openStackMachineClass *machine.OpenStackMachineClass) (result *machine.OpenStackMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(openstackmachineclassesResource, c.ns, openStackMachineClass), &machine.OpenStackMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.OpenStackMachineClass), err
}

// Delete takes name of the openStackMachineClass and deletes it. Returns an error if one occurs.
func (c *FakeOpenStackMachineClasses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(openstackmachineclassesResource, c.ns, name), &machine.OpenStackMachineClass{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOpenStackMachineClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(openstackmachineclassesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &machine.OpenStackMachineClassList{})
	return err
}

// Patch applies the patch and returns the patched openStackMachineClass.
func (c *FakeOpenStackMachineClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *machine.OpenStackMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(openstackmachineclassesResource, c.ns, name, pt, data, subresources...), &machine.OpenStackMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.OpenStackMachineClass), err
}
