// +build !ignore_autogenerated

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	machine "github.com/gardener/node-controller-manager/pkg/apis/machine"
	v1 "k8s.io/api/core/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_AWSBlockDeviceMappingSpec_To_machine_AWSBlockDeviceMappingSpec,
		Convert_machine_AWSBlockDeviceMappingSpec_To_v1alpha1_AWSBlockDeviceMappingSpec,
		Convert_v1alpha1_AWSEbsBlockDeviceSpec_To_machine_AWSEbsBlockDeviceSpec,
		Convert_machine_AWSEbsBlockDeviceSpec_To_v1alpha1_AWSEbsBlockDeviceSpec,
		Convert_v1alpha1_AWSIAMProfileSpec_To_machine_AWSIAMProfileSpec,
		Convert_machine_AWSIAMProfileSpec_To_v1alpha1_AWSIAMProfileSpec,
		Convert_v1alpha1_AWSMachineClass_To_machine_AWSMachineClass,
		Convert_machine_AWSMachineClass_To_v1alpha1_AWSMachineClass,
		Convert_v1alpha1_AWSMachineClassList_To_machine_AWSMachineClassList,
		Convert_machine_AWSMachineClassList_To_v1alpha1_AWSMachineClassList,
		Convert_v1alpha1_AWSMachineClassSpec_To_machine_AWSMachineClassSpec,
		Convert_machine_AWSMachineClassSpec_To_v1alpha1_AWSMachineClassSpec,
		Convert_v1alpha1_AWSNetworkInterfaceSpec_To_machine_AWSNetworkInterfaceSpec,
		Convert_machine_AWSNetworkInterfaceSpec_To_v1alpha1_AWSNetworkInterfaceSpec,
		Convert_v1alpha1_ClassSpec_To_machine_ClassSpec,
		Convert_machine_ClassSpec_To_v1alpha1_ClassSpec,
		Convert_v1alpha1_CurrentStatus_To_machine_CurrentStatus,
		Convert_machine_CurrentStatus_To_v1alpha1_CurrentStatus,
		Convert_v1alpha1_LastOperation_To_machine_LastOperation,
		Convert_machine_LastOperation_To_v1alpha1_LastOperation,
		Convert_v1alpha1_Machine_To_machine_Machine,
		Convert_machine_Machine_To_v1alpha1_Machine,
		Convert_v1alpha1_MachineDeployment_To_machine_MachineDeployment,
		Convert_machine_MachineDeployment_To_v1alpha1_MachineDeployment,
		Convert_v1alpha1_MachineDeploymentCondition_To_machine_MachineDeploymentCondition,
		Convert_machine_MachineDeploymentCondition_To_v1alpha1_MachineDeploymentCondition,
		Convert_v1alpha1_MachineDeploymentList_To_machine_MachineDeploymentList,
		Convert_machine_MachineDeploymentList_To_v1alpha1_MachineDeploymentList,
		Convert_v1alpha1_MachineDeploymentRollback_To_machine_MachineDeploymentRollback,
		Convert_machine_MachineDeploymentRollback_To_v1alpha1_MachineDeploymentRollback,
		Convert_v1alpha1_MachineDeploymentSpec_To_machine_MachineDeploymentSpec,
		Convert_machine_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec,
		Convert_v1alpha1_MachineDeploymentStatus_To_machine_MachineDeploymentStatus,
		Convert_machine_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus,
		Convert_v1alpha1_MachineDeploymentStrategy_To_machine_MachineDeploymentStrategy,
		Convert_machine_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy,
		Convert_v1alpha1_MachineList_To_machine_MachineList,
		Convert_machine_MachineList_To_v1alpha1_MachineList,
		Convert_v1alpha1_MachineSet_To_machine_MachineSet,
		Convert_machine_MachineSet_To_v1alpha1_MachineSet,
		Convert_v1alpha1_MachineSetCondition_To_machine_MachineSetCondition,
		Convert_machine_MachineSetCondition_To_v1alpha1_MachineSetCondition,
		Convert_v1alpha1_MachineSetList_To_machine_MachineSetList,
		Convert_machine_MachineSetList_To_v1alpha1_MachineSetList,
		Convert_v1alpha1_MachineSetSpec_To_machine_MachineSetSpec,
		Convert_machine_MachineSetSpec_To_v1alpha1_MachineSetSpec,
		Convert_v1alpha1_MachineSetStatus_To_machine_MachineSetStatus,
		Convert_machine_MachineSetStatus_To_v1alpha1_MachineSetStatus,
		Convert_v1alpha1_MachineSpec_To_machine_MachineSpec,
		Convert_machine_MachineSpec_To_v1alpha1_MachineSpec,
		Convert_v1alpha1_MachineStatus_To_machine_MachineStatus,
		Convert_machine_MachineStatus_To_v1alpha1_MachineStatus,
		Convert_v1alpha1_MachineTemplate_To_machine_MachineTemplate,
		Convert_machine_MachineTemplate_To_v1alpha1_MachineTemplate,
		Convert_v1alpha1_MachineTemplateList_To_machine_MachineTemplateList,
		Convert_machine_MachineTemplateList_To_v1alpha1_MachineTemplateList,
		Convert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec,
		Convert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec,
		Convert_v1alpha1_RollbackConfig_To_machine_RollbackConfig,
		Convert_machine_RollbackConfig_To_v1alpha1_RollbackConfig,
		Convert_v1alpha1_RollingUpdateMachineDeployment_To_machine_RollingUpdateMachineDeployment,
		Convert_machine_RollingUpdateMachineDeployment_To_v1alpha1_RollingUpdateMachineDeployment,
		Convert_v1alpha1_Scale_To_machine_Scale,
		Convert_machine_Scale_To_v1alpha1_Scale,
		Convert_v1alpha1_ScaleSpec_To_machine_ScaleSpec,
		Convert_machine_ScaleSpec_To_v1alpha1_ScaleSpec,
		Convert_v1alpha1_ScaleStatus_To_machine_ScaleStatus,
		Convert_machine_ScaleStatus_To_v1alpha1_ScaleStatus,
	)
}

func autoConvert_v1alpha1_AWSBlockDeviceMappingSpec_To_machine_AWSBlockDeviceMappingSpec(in *AWSBlockDeviceMappingSpec, out *machine.AWSBlockDeviceMappingSpec, s conversion.Scope) error {
	out.DeviceName = in.DeviceName
	if err := Convert_v1alpha1_AWSEbsBlockDeviceSpec_To_machine_AWSEbsBlockDeviceSpec(&in.Ebs, &out.Ebs, s); err != nil {
		return err
	}
	out.NoDevice = in.NoDevice
	out.VirtualName = in.VirtualName
	return nil
}

// Convert_v1alpha1_AWSBlockDeviceMappingSpec_To_machine_AWSBlockDeviceMappingSpec is an autogenerated conversion function.
func Convert_v1alpha1_AWSBlockDeviceMappingSpec_To_machine_AWSBlockDeviceMappingSpec(in *AWSBlockDeviceMappingSpec, out *machine.AWSBlockDeviceMappingSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSBlockDeviceMappingSpec_To_machine_AWSBlockDeviceMappingSpec(in, out, s)
}

func autoConvert_machine_AWSBlockDeviceMappingSpec_To_v1alpha1_AWSBlockDeviceMappingSpec(in *machine.AWSBlockDeviceMappingSpec, out *AWSBlockDeviceMappingSpec, s conversion.Scope) error {
	out.DeviceName = in.DeviceName
	if err := Convert_machine_AWSEbsBlockDeviceSpec_To_v1alpha1_AWSEbsBlockDeviceSpec(&in.Ebs, &out.Ebs, s); err != nil {
		return err
	}
	out.NoDevice = in.NoDevice
	out.VirtualName = in.VirtualName
	return nil
}

// Convert_machine_AWSBlockDeviceMappingSpec_To_v1alpha1_AWSBlockDeviceMappingSpec is an autogenerated conversion function.
func Convert_machine_AWSBlockDeviceMappingSpec_To_v1alpha1_AWSBlockDeviceMappingSpec(in *machine.AWSBlockDeviceMappingSpec, out *AWSBlockDeviceMappingSpec, s conversion.Scope) error {
	return autoConvert_machine_AWSBlockDeviceMappingSpec_To_v1alpha1_AWSBlockDeviceMappingSpec(in, out, s)
}

func autoConvert_v1alpha1_AWSEbsBlockDeviceSpec_To_machine_AWSEbsBlockDeviceSpec(in *AWSEbsBlockDeviceSpec, out *machine.AWSEbsBlockDeviceSpec, s conversion.Scope) error {
	out.DeleteOnTermination = in.DeleteOnTermination
	out.Encrypted = in.Encrypted
	out.Iops = in.Iops
	out.VolumeSize = in.VolumeSize
	out.VolumeType = in.VolumeType
	return nil
}

// Convert_v1alpha1_AWSEbsBlockDeviceSpec_To_machine_AWSEbsBlockDeviceSpec is an autogenerated conversion function.
func Convert_v1alpha1_AWSEbsBlockDeviceSpec_To_machine_AWSEbsBlockDeviceSpec(in *AWSEbsBlockDeviceSpec, out *machine.AWSEbsBlockDeviceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSEbsBlockDeviceSpec_To_machine_AWSEbsBlockDeviceSpec(in, out, s)
}

func autoConvert_machine_AWSEbsBlockDeviceSpec_To_v1alpha1_AWSEbsBlockDeviceSpec(in *machine.AWSEbsBlockDeviceSpec, out *AWSEbsBlockDeviceSpec, s conversion.Scope) error {
	out.DeleteOnTermination = in.DeleteOnTermination
	out.Encrypted = in.Encrypted
	out.Iops = in.Iops
	out.VolumeSize = in.VolumeSize
	out.VolumeType = in.VolumeType
	return nil
}

// Convert_machine_AWSEbsBlockDeviceSpec_To_v1alpha1_AWSEbsBlockDeviceSpec is an autogenerated conversion function.
func Convert_machine_AWSEbsBlockDeviceSpec_To_v1alpha1_AWSEbsBlockDeviceSpec(in *machine.AWSEbsBlockDeviceSpec, out *AWSEbsBlockDeviceSpec, s conversion.Scope) error {
	return autoConvert_machine_AWSEbsBlockDeviceSpec_To_v1alpha1_AWSEbsBlockDeviceSpec(in, out, s)
}

func autoConvert_v1alpha1_AWSIAMProfileSpec_To_machine_AWSIAMProfileSpec(in *AWSIAMProfileSpec, out *machine.AWSIAMProfileSpec, s conversion.Scope) error {
	out.ARN = in.ARN
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_AWSIAMProfileSpec_To_machine_AWSIAMProfileSpec is an autogenerated conversion function.
func Convert_v1alpha1_AWSIAMProfileSpec_To_machine_AWSIAMProfileSpec(in *AWSIAMProfileSpec, out *machine.AWSIAMProfileSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSIAMProfileSpec_To_machine_AWSIAMProfileSpec(in, out, s)
}

func autoConvert_machine_AWSIAMProfileSpec_To_v1alpha1_AWSIAMProfileSpec(in *machine.AWSIAMProfileSpec, out *AWSIAMProfileSpec, s conversion.Scope) error {
	out.ARN = in.ARN
	out.Name = in.Name
	return nil
}

// Convert_machine_AWSIAMProfileSpec_To_v1alpha1_AWSIAMProfileSpec is an autogenerated conversion function.
func Convert_machine_AWSIAMProfileSpec_To_v1alpha1_AWSIAMProfileSpec(in *machine.AWSIAMProfileSpec, out *AWSIAMProfileSpec, s conversion.Scope) error {
	return autoConvert_machine_AWSIAMProfileSpec_To_v1alpha1_AWSIAMProfileSpec(in, out, s)
}

func autoConvert_v1alpha1_AWSMachineClass_To_machine_AWSMachineClass(in *AWSMachineClass, out *machine.AWSMachineClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_AWSMachineClassSpec_To_machine_AWSMachineClassSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AWSMachineClass_To_machine_AWSMachineClass is an autogenerated conversion function.
func Convert_v1alpha1_AWSMachineClass_To_machine_AWSMachineClass(in *AWSMachineClass, out *machine.AWSMachineClass, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSMachineClass_To_machine_AWSMachineClass(in, out, s)
}

func autoConvert_machine_AWSMachineClass_To_v1alpha1_AWSMachineClass(in *machine.AWSMachineClass, out *AWSMachineClass, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_machine_AWSMachineClassSpec_To_v1alpha1_AWSMachineClassSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_AWSMachineClass_To_v1alpha1_AWSMachineClass is an autogenerated conversion function.
func Convert_machine_AWSMachineClass_To_v1alpha1_AWSMachineClass(in *machine.AWSMachineClass, out *AWSMachineClass, s conversion.Scope) error {
	return autoConvert_machine_AWSMachineClass_To_v1alpha1_AWSMachineClass(in, out, s)
}

func autoConvert_v1alpha1_AWSMachineClassList_To_machine_AWSMachineClassList(in *AWSMachineClassList, out *machine.AWSMachineClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]machine.AWSMachineClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_AWSMachineClassList_To_machine_AWSMachineClassList is an autogenerated conversion function.
func Convert_v1alpha1_AWSMachineClassList_To_machine_AWSMachineClassList(in *AWSMachineClassList, out *machine.AWSMachineClassList, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSMachineClassList_To_machine_AWSMachineClassList(in, out, s)
}

func autoConvert_machine_AWSMachineClassList_To_v1alpha1_AWSMachineClassList(in *machine.AWSMachineClassList, out *AWSMachineClassList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AWSMachineClass)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_machine_AWSMachineClassList_To_v1alpha1_AWSMachineClassList is an autogenerated conversion function.
func Convert_machine_AWSMachineClassList_To_v1alpha1_AWSMachineClassList(in *machine.AWSMachineClassList, out *AWSMachineClassList, s conversion.Scope) error {
	return autoConvert_machine_AWSMachineClassList_To_v1alpha1_AWSMachineClassList(in, out, s)
}

func autoConvert_v1alpha1_AWSMachineClassSpec_To_machine_AWSMachineClassSpec(in *AWSMachineClassSpec, out *machine.AWSMachineClassSpec, s conversion.Scope) error {
	out.AMI = in.AMI
	out.AvailabilityZone = in.AvailabilityZone
	out.BlockDevices = *(*[]machine.AWSBlockDeviceMappingSpec)(unsafe.Pointer(&in.BlockDevices))
	out.EbsOptimized = in.EbsOptimized
	if err := Convert_v1alpha1_AWSIAMProfileSpec_To_machine_AWSIAMProfileSpec(&in.IAM, &out.IAM, s); err != nil {
		return err
	}
	out.MachineType = in.MachineType
	out.KeyName = in.KeyName
	out.Monitoring = in.Monitoring
	out.NetworkInterfaces = *(*[]machine.AWSNetworkInterfaceSpec)(unsafe.Pointer(&in.NetworkInterfaces))
	out.Tags = *(*map[string]string)(unsafe.Pointer(&in.Tags))
	out.SecretRef = (*v1.SecretReference)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_v1alpha1_AWSMachineClassSpec_To_machine_AWSMachineClassSpec is an autogenerated conversion function.
func Convert_v1alpha1_AWSMachineClassSpec_To_machine_AWSMachineClassSpec(in *AWSMachineClassSpec, out *machine.AWSMachineClassSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSMachineClassSpec_To_machine_AWSMachineClassSpec(in, out, s)
}

func autoConvert_machine_AWSMachineClassSpec_To_v1alpha1_AWSMachineClassSpec(in *machine.AWSMachineClassSpec, out *AWSMachineClassSpec, s conversion.Scope) error {
	out.AMI = in.AMI
	out.AvailabilityZone = in.AvailabilityZone
	out.BlockDevices = *(*[]AWSBlockDeviceMappingSpec)(unsafe.Pointer(&in.BlockDevices))
	out.EbsOptimized = in.EbsOptimized
	if err := Convert_machine_AWSIAMProfileSpec_To_v1alpha1_AWSIAMProfileSpec(&in.IAM, &out.IAM, s); err != nil {
		return err
	}
	out.MachineType = in.MachineType
	out.KeyName = in.KeyName
	out.Monitoring = in.Monitoring
	out.NetworkInterfaces = *(*[]AWSNetworkInterfaceSpec)(unsafe.Pointer(&in.NetworkInterfaces))
	out.Tags = *(*map[string]string)(unsafe.Pointer(&in.Tags))
	out.SecretRef = (*v1.SecretReference)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_machine_AWSMachineClassSpec_To_v1alpha1_AWSMachineClassSpec is an autogenerated conversion function.
func Convert_machine_AWSMachineClassSpec_To_v1alpha1_AWSMachineClassSpec(in *machine.AWSMachineClassSpec, out *AWSMachineClassSpec, s conversion.Scope) error {
	return autoConvert_machine_AWSMachineClassSpec_To_v1alpha1_AWSMachineClassSpec(in, out, s)
}

func autoConvert_v1alpha1_AWSNetworkInterfaceSpec_To_machine_AWSNetworkInterfaceSpec(in *AWSNetworkInterfaceSpec, out *machine.AWSNetworkInterfaceSpec, s conversion.Scope) error {
	out.AssociatePublicIPAddress = in.AssociatePublicIPAddress
	out.DeleteOnTermination = in.DeleteOnTermination
	out.Description = in.Description
	out.SecurityGroupID = *(*[]string)(unsafe.Pointer(&in.SecurityGroupID))
	out.SubnetID = in.SubnetID
	return nil
}

// Convert_v1alpha1_AWSNetworkInterfaceSpec_To_machine_AWSNetworkInterfaceSpec is an autogenerated conversion function.
func Convert_v1alpha1_AWSNetworkInterfaceSpec_To_machine_AWSNetworkInterfaceSpec(in *AWSNetworkInterfaceSpec, out *machine.AWSNetworkInterfaceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSNetworkInterfaceSpec_To_machine_AWSNetworkInterfaceSpec(in, out, s)
}

func autoConvert_machine_AWSNetworkInterfaceSpec_To_v1alpha1_AWSNetworkInterfaceSpec(in *machine.AWSNetworkInterfaceSpec, out *AWSNetworkInterfaceSpec, s conversion.Scope) error {
	out.AssociatePublicIPAddress = in.AssociatePublicIPAddress
	out.DeleteOnTermination = in.DeleteOnTermination
	out.Description = in.Description
	out.SecurityGroupID = *(*[]string)(unsafe.Pointer(&in.SecurityGroupID))
	out.SubnetID = in.SubnetID
	return nil
}

// Convert_machine_AWSNetworkInterfaceSpec_To_v1alpha1_AWSNetworkInterfaceSpec is an autogenerated conversion function.
func Convert_machine_AWSNetworkInterfaceSpec_To_v1alpha1_AWSNetworkInterfaceSpec(in *machine.AWSNetworkInterfaceSpec, out *AWSNetworkInterfaceSpec, s conversion.Scope) error {
	return autoConvert_machine_AWSNetworkInterfaceSpec_To_v1alpha1_AWSNetworkInterfaceSpec(in, out, s)
}

func autoConvert_v1alpha1_ClassSpec_To_machine_ClassSpec(in *ClassSpec, out *machine.ClassSpec, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ClassSpec_To_machine_ClassSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClassSpec_To_machine_ClassSpec(in *ClassSpec, out *machine.ClassSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClassSpec_To_machine_ClassSpec(in, out, s)
}

func autoConvert_machine_ClassSpec_To_v1alpha1_ClassSpec(in *machine.ClassSpec, out *ClassSpec, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_machine_ClassSpec_To_v1alpha1_ClassSpec is an autogenerated conversion function.
func Convert_machine_ClassSpec_To_v1alpha1_ClassSpec(in *machine.ClassSpec, out *ClassSpec, s conversion.Scope) error {
	return autoConvert_machine_ClassSpec_To_v1alpha1_ClassSpec(in, out, s)
}

func autoConvert_v1alpha1_CurrentStatus_To_machine_CurrentStatus(in *CurrentStatus, out *machine.CurrentStatus, s conversion.Scope) error {
	out.Phase = machine.MachinePhase(in.Phase)
	out.TimeoutActive = in.TimeoutActive
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_v1alpha1_CurrentStatus_To_machine_CurrentStatus is an autogenerated conversion function.
func Convert_v1alpha1_CurrentStatus_To_machine_CurrentStatus(in *CurrentStatus, out *machine.CurrentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CurrentStatus_To_machine_CurrentStatus(in, out, s)
}

func autoConvert_machine_CurrentStatus_To_v1alpha1_CurrentStatus(in *machine.CurrentStatus, out *CurrentStatus, s conversion.Scope) error {
	out.Phase = MachinePhase(in.Phase)
	out.TimeoutActive = in.TimeoutActive
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_machine_CurrentStatus_To_v1alpha1_CurrentStatus is an autogenerated conversion function.
func Convert_machine_CurrentStatus_To_v1alpha1_CurrentStatus(in *machine.CurrentStatus, out *CurrentStatus, s conversion.Scope) error {
	return autoConvert_machine_CurrentStatus_To_v1alpha1_CurrentStatus(in, out, s)
}

func autoConvert_v1alpha1_LastOperation_To_machine_LastOperation(in *LastOperation, out *machine.LastOperation, s conversion.Scope) error {
	out.Description = in.Description
	out.LastUpdateTime = in.LastUpdateTime
	out.State = machine.MachineState(in.State)
	out.Type = in.Type
	return nil
}

// Convert_v1alpha1_LastOperation_To_machine_LastOperation is an autogenerated conversion function.
func Convert_v1alpha1_LastOperation_To_machine_LastOperation(in *LastOperation, out *machine.LastOperation, s conversion.Scope) error {
	return autoConvert_v1alpha1_LastOperation_To_machine_LastOperation(in, out, s)
}

func autoConvert_machine_LastOperation_To_v1alpha1_LastOperation(in *machine.LastOperation, out *LastOperation, s conversion.Scope) error {
	out.Description = in.Description
	out.LastUpdateTime = in.LastUpdateTime
	out.State = MachineState(in.State)
	out.Type = in.Type
	return nil
}

// Convert_machine_LastOperation_To_v1alpha1_LastOperation is an autogenerated conversion function.
func Convert_machine_LastOperation_To_v1alpha1_LastOperation(in *machine.LastOperation, out *LastOperation, s conversion.Scope) error {
	return autoConvert_machine_LastOperation_To_v1alpha1_LastOperation(in, out, s)
}

func autoConvert_v1alpha1_Machine_To_machine_Machine(in *Machine, out *machine.Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSpec_To_machine_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineStatus_To_machine_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Machine_To_machine_Machine is an autogenerated conversion function.
func Convert_v1alpha1_Machine_To_machine_Machine(in *Machine, out *machine.Machine, s conversion.Scope) error {
	return autoConvert_v1alpha1_Machine_To_machine_Machine(in, out, s)
}

func autoConvert_machine_Machine_To_v1alpha1_Machine(in *machine.Machine, out *Machine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_machine_MachineSpec_To_v1alpha1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_machine_MachineStatus_To_v1alpha1_MachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_Machine_To_v1alpha1_Machine is an autogenerated conversion function.
func Convert_machine_Machine_To_v1alpha1_Machine(in *machine.Machine, out *Machine, s conversion.Scope) error {
	return autoConvert_machine_Machine_To_v1alpha1_Machine(in, out, s)
}

func autoConvert_v1alpha1_MachineDeployment_To_machine_MachineDeployment(in *MachineDeployment, out *machine.MachineDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineDeploymentSpec_To_machine_MachineDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineDeploymentStatus_To_machine_MachineDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineDeployment_To_machine_MachineDeployment is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeployment_To_machine_MachineDeployment(in *MachineDeployment, out *machine.MachineDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeployment_To_machine_MachineDeployment(in, out, s)
}

func autoConvert_machine_MachineDeployment_To_v1alpha1_MachineDeployment(in *machine.MachineDeployment, out *MachineDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_machine_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_machine_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_MachineDeployment_To_v1alpha1_MachineDeployment is an autogenerated conversion function.
func Convert_machine_MachineDeployment_To_v1alpha1_MachineDeployment(in *machine.MachineDeployment, out *MachineDeployment, s conversion.Scope) error {
	return autoConvert_machine_MachineDeployment_To_v1alpha1_MachineDeployment(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentCondition_To_machine_MachineDeploymentCondition(in *MachineDeploymentCondition, out *machine.MachineDeploymentCondition, s conversion.Scope) error {
	out.Type = machine.MachineDeploymentConditionType(in.Type)
	out.Status = machine.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_MachineDeploymentCondition_To_machine_MachineDeploymentCondition is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentCondition_To_machine_MachineDeploymentCondition(in *MachineDeploymentCondition, out *machine.MachineDeploymentCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentCondition_To_machine_MachineDeploymentCondition(in, out, s)
}

func autoConvert_machine_MachineDeploymentCondition_To_v1alpha1_MachineDeploymentCondition(in *machine.MachineDeploymentCondition, out *MachineDeploymentCondition, s conversion.Scope) error {
	out.Type = MachineDeploymentConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_machine_MachineDeploymentCondition_To_v1alpha1_MachineDeploymentCondition is an autogenerated conversion function.
func Convert_machine_MachineDeploymentCondition_To_v1alpha1_MachineDeploymentCondition(in *machine.MachineDeploymentCondition, out *MachineDeploymentCondition, s conversion.Scope) error {
	return autoConvert_machine_MachineDeploymentCondition_To_v1alpha1_MachineDeploymentCondition(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentList_To_machine_MachineDeploymentList(in *MachineDeploymentList, out *machine.MachineDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]machine.MachineDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineDeploymentList_To_machine_MachineDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentList_To_machine_MachineDeploymentList(in *MachineDeploymentList, out *machine.MachineDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentList_To_machine_MachineDeploymentList(in, out, s)
}

func autoConvert_machine_MachineDeploymentList_To_v1alpha1_MachineDeploymentList(in *machine.MachineDeploymentList, out *MachineDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MachineDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_machine_MachineDeploymentList_To_v1alpha1_MachineDeploymentList is an autogenerated conversion function.
func Convert_machine_MachineDeploymentList_To_v1alpha1_MachineDeploymentList(in *machine.MachineDeploymentList, out *MachineDeploymentList, s conversion.Scope) error {
	return autoConvert_machine_MachineDeploymentList_To_v1alpha1_MachineDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentRollback_To_machine_MachineDeploymentRollback(in *MachineDeploymentRollback, out *machine.MachineDeploymentRollback, s conversion.Scope) error {
	out.Name = in.Name
	out.UpdatedAnnotations = *(*map[string]string)(unsafe.Pointer(&in.UpdatedAnnotations))
	if err := Convert_v1alpha1_RollbackConfig_To_machine_RollbackConfig(&in.RollbackTo, &out.RollbackTo, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineDeploymentRollback_To_machine_MachineDeploymentRollback is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentRollback_To_machine_MachineDeploymentRollback(in *MachineDeploymentRollback, out *machine.MachineDeploymentRollback, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentRollback_To_machine_MachineDeploymentRollback(in, out, s)
}

func autoConvert_machine_MachineDeploymentRollback_To_v1alpha1_MachineDeploymentRollback(in *machine.MachineDeploymentRollback, out *MachineDeploymentRollback, s conversion.Scope) error {
	out.Name = in.Name
	out.UpdatedAnnotations = *(*map[string]string)(unsafe.Pointer(&in.UpdatedAnnotations))
	if err := Convert_machine_RollbackConfig_To_v1alpha1_RollbackConfig(&in.RollbackTo, &out.RollbackTo, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_MachineDeploymentRollback_To_v1alpha1_MachineDeploymentRollback is an autogenerated conversion function.
func Convert_machine_MachineDeploymentRollback_To_v1alpha1_MachineDeploymentRollback(in *machine.MachineDeploymentRollback, out *MachineDeploymentRollback, s conversion.Scope) error {
	return autoConvert_machine_MachineDeploymentRollback_To_v1alpha1_MachineDeploymentRollback(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentSpec_To_machine_MachineDeploymentSpec(in *MachineDeploymentSpec, out *machine.MachineDeploymentSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineDeploymentStrategy_To_machine_MachineDeploymentStrategy(&in.Strategy, &out.Strategy, s); err != nil {
		return err
	}
	out.MinReadySeconds = in.MinReadySeconds
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Paused = in.Paused
	out.RollbackTo = (*machine.RollbackConfig)(unsafe.Pointer(in.RollbackTo))
	out.ProgressDeadlineSeconds = (*int32)(unsafe.Pointer(in.ProgressDeadlineSeconds))
	return nil
}

// Convert_v1alpha1_MachineDeploymentSpec_To_machine_MachineDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentSpec_To_machine_MachineDeploymentSpec(in *MachineDeploymentSpec, out *machine.MachineDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentSpec_To_machine_MachineDeploymentSpec(in, out, s)
}

func autoConvert_machine_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec(in *machine.MachineDeploymentSpec, out *MachineDeploymentSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	if err := Convert_machine_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy(&in.Strategy, &out.Strategy, s); err != nil {
		return err
	}
	out.MinReadySeconds = in.MinReadySeconds
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Paused = in.Paused
	out.RollbackTo = (*RollbackConfig)(unsafe.Pointer(in.RollbackTo))
	out.ProgressDeadlineSeconds = (*int32)(unsafe.Pointer(in.ProgressDeadlineSeconds))
	return nil
}

// Convert_machine_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec is an autogenerated conversion function.
func Convert_machine_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec(in *machine.MachineDeploymentSpec, out *MachineDeploymentSpec, s conversion.Scope) error {
	return autoConvert_machine_MachineDeploymentSpec_To_v1alpha1_MachineDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentStatus_To_machine_MachineDeploymentStatus(in *MachineDeploymentStatus, out *machine.MachineDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	out.Conditions = *(*[]machine.MachineDeploymentCondition)(unsafe.Pointer(&in.Conditions))
	out.CollisionCount = (*int32)(unsafe.Pointer(in.CollisionCount))
	return nil
}

// Convert_v1alpha1_MachineDeploymentStatus_To_machine_MachineDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentStatus_To_machine_MachineDeploymentStatus(in *MachineDeploymentStatus, out *machine.MachineDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentStatus_To_machine_MachineDeploymentStatus(in, out, s)
}

func autoConvert_machine_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus(in *machine.MachineDeploymentStatus, out *MachineDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	out.Conditions = *(*[]MachineDeploymentCondition)(unsafe.Pointer(&in.Conditions))
	out.CollisionCount = (*int32)(unsafe.Pointer(in.CollisionCount))
	return nil
}

// Convert_machine_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus is an autogenerated conversion function.
func Convert_machine_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus(in *machine.MachineDeploymentStatus, out *MachineDeploymentStatus, s conversion.Scope) error {
	return autoConvert_machine_MachineDeploymentStatus_To_v1alpha1_MachineDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineDeploymentStrategy_To_machine_MachineDeploymentStrategy(in *MachineDeploymentStrategy, out *machine.MachineDeploymentStrategy, s conversion.Scope) error {
	out.Type = machine.MachineDeploymentStrategyType(in.Type)
	out.RollingUpdate = (*machine.RollingUpdateMachineDeployment)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_v1alpha1_MachineDeploymentStrategy_To_machine_MachineDeploymentStrategy is an autogenerated conversion function.
func Convert_v1alpha1_MachineDeploymentStrategy_To_machine_MachineDeploymentStrategy(in *MachineDeploymentStrategy, out *machine.MachineDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineDeploymentStrategy_To_machine_MachineDeploymentStrategy(in, out, s)
}

func autoConvert_machine_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy(in *machine.MachineDeploymentStrategy, out *MachineDeploymentStrategy, s conversion.Scope) error {
	out.Type = MachineDeploymentStrategyType(in.Type)
	out.RollingUpdate = (*RollingUpdateMachineDeployment)(unsafe.Pointer(in.RollingUpdate))
	return nil
}

// Convert_machine_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy is an autogenerated conversion function.
func Convert_machine_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy(in *machine.MachineDeploymentStrategy, out *MachineDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_machine_MachineDeploymentStrategy_To_v1alpha1_MachineDeploymentStrategy(in, out, s)
}

func autoConvert_v1alpha1_MachineList_To_machine_MachineList(in *MachineList, out *machine.MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]machine.Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineList_To_machine_MachineList is an autogenerated conversion function.
func Convert_v1alpha1_MachineList_To_machine_MachineList(in *MachineList, out *machine.MachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineList_To_machine_MachineList(in, out, s)
}

func autoConvert_machine_MachineList_To_v1alpha1_MachineList(in *machine.MachineList, out *MachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Machine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_machine_MachineList_To_v1alpha1_MachineList is an autogenerated conversion function.
func Convert_machine_MachineList_To_v1alpha1_MachineList(in *machine.MachineList, out *MachineList, s conversion.Scope) error {
	return autoConvert_machine_MachineList_To_v1alpha1_MachineList(in, out, s)
}

func autoConvert_v1alpha1_MachineSet_To_machine_MachineSet(in *MachineSet, out *machine.MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSetSpec_To_machine_MachineSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineSetStatus_To_machine_MachineSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineSet_To_machine_MachineSet is an autogenerated conversion function.
func Convert_v1alpha1_MachineSet_To_machine_MachineSet(in *MachineSet, out *machine.MachineSet, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSet_To_machine_MachineSet(in, out, s)
}

func autoConvert_machine_MachineSet_To_v1alpha1_MachineSet(in *machine.MachineSet, out *MachineSet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_machine_MachineSetSpec_To_v1alpha1_MachineSetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_machine_MachineSetStatus_To_v1alpha1_MachineSetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_MachineSet_To_v1alpha1_MachineSet is an autogenerated conversion function.
func Convert_machine_MachineSet_To_v1alpha1_MachineSet(in *machine.MachineSet, out *MachineSet, s conversion.Scope) error {
	return autoConvert_machine_MachineSet_To_v1alpha1_MachineSet(in, out, s)
}

func autoConvert_v1alpha1_MachineSetCondition_To_machine_MachineSetCondition(in *MachineSetCondition, out *machine.MachineSetCondition, s conversion.Scope) error {
	out.Type = machine.MachineSetConditionType(in.Type)
	out.Status = machine.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_MachineSetCondition_To_machine_MachineSetCondition is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetCondition_To_machine_MachineSetCondition(in *MachineSetCondition, out *machine.MachineSetCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetCondition_To_machine_MachineSetCondition(in, out, s)
}

func autoConvert_machine_MachineSetCondition_To_v1alpha1_MachineSetCondition(in *machine.MachineSetCondition, out *MachineSetCondition, s conversion.Scope) error {
	out.Type = MachineSetConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_machine_MachineSetCondition_To_v1alpha1_MachineSetCondition is an autogenerated conversion function.
func Convert_machine_MachineSetCondition_To_v1alpha1_MachineSetCondition(in *machine.MachineSetCondition, out *MachineSetCondition, s conversion.Scope) error {
	return autoConvert_machine_MachineSetCondition_To_v1alpha1_MachineSetCondition(in, out, s)
}

func autoConvert_v1alpha1_MachineSetList_To_machine_MachineSetList(in *MachineSetList, out *machine.MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]machine.MachineSet, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_MachineSet_To_machine_MachineSet(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_MachineSetList_To_machine_MachineSetList is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetList_To_machine_MachineSetList(in *MachineSetList, out *machine.MachineSetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetList_To_machine_MachineSetList(in, out, s)
}

func autoConvert_machine_MachineSetList_To_v1alpha1_MachineSetList(in *machine.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineSet, len(*in))
		for i := range *in {
			if err := Convert_machine_MachineSet_To_v1alpha1_MachineSet(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_machine_MachineSetList_To_v1alpha1_MachineSetList is an autogenerated conversion function.
func Convert_machine_MachineSetList_To_v1alpha1_MachineSetList(in *machine.MachineSetList, out *MachineSetList, s conversion.Scope) error {
	return autoConvert_machine_MachineSetList_To_v1alpha1_MachineSetList(in, out, s)
}

func autoConvert_v1alpha1_MachineSetSpec_To_machine_MachineSetSpec(in *MachineSetSpec, out *machine.MachineSetSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_v1alpha1_ClassSpec_To_machine_ClassSpec(&in.MachineClass, &out.MachineClass, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.MinReadySeconds = int(in.MinReadySeconds)
	return nil
}

// Convert_v1alpha1_MachineSetSpec_To_machine_MachineSetSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetSpec_To_machine_MachineSetSpec(in *MachineSetSpec, out *machine.MachineSetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetSpec_To_machine_MachineSetSpec(in, out, s)
}

func autoConvert_machine_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *machine.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_machine_ClassSpec_To_v1alpha1_ClassSpec(&in.MachineClass, &out.MachineClass, s); err != nil {
		return err
	}
	if err := Convert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.MinReadySeconds = int32(in.MinReadySeconds)
	return nil
}

// Convert_machine_MachineSetSpec_To_v1alpha1_MachineSetSpec is an autogenerated conversion function.
func Convert_machine_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *machine.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	return autoConvert_machine_MachineSetSpec_To_v1alpha1_MachineSetSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSetStatus_To_machine_MachineSetStatus(in *MachineSetStatus, out *machine.MachineSetStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_LastOperation_To_machine_LastOperation(&in.LastOperation, &out.LastOperation, s); err != nil {
		return err
	}
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.Conditions = *(*[]machine.MachineSetCondition)(unsafe.Pointer(&in.Conditions))
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1alpha1_MachineSetStatus_To_machine_MachineSetStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetStatus_To_machine_MachineSetStatus(in *MachineSetStatus, out *machine.MachineSetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetStatus_To_machine_MachineSetStatus(in, out, s)
}

func autoConvert_machine_MachineSetStatus_To_v1alpha1_MachineSetStatus(in *machine.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	if err := Convert_machine_LastOperation_To_v1alpha1_LastOperation(&in.LastOperation, &out.LastOperation, s); err != nil {
		return err
	}
	out.Replicas = in.Replicas
	out.FullyLabeledReplicas = in.FullyLabeledReplicas
	out.ReadyReplicas = in.ReadyReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.Conditions = *(*[]MachineSetCondition)(unsafe.Pointer(&in.Conditions))
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_machine_MachineSetStatus_To_v1alpha1_MachineSetStatus is an autogenerated conversion function.
func Convert_machine_MachineSetStatus_To_v1alpha1_MachineSetStatus(in *machine.MachineSetStatus, out *MachineSetStatus, s conversion.Scope) error {
	return autoConvert_machine_MachineSetStatus_To_v1alpha1_MachineSetStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineSpec_To_machine_MachineSpec(in *MachineSpec, out *machine.MachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ClassSpec_To_machine_ClassSpec(&in.Class, &out.Class, s); err != nil {
		return err
	}
	out.ProviderID = in.ProviderID
	return nil
}

// Convert_v1alpha1_MachineSpec_To_machine_MachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSpec_To_machine_MachineSpec(in *MachineSpec, out *machine.MachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSpec_To_machine_MachineSpec(in, out, s)
}

func autoConvert_machine_MachineSpec_To_v1alpha1_MachineSpec(in *machine.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	if err := Convert_machine_ClassSpec_To_v1alpha1_ClassSpec(&in.Class, &out.Class, s); err != nil {
		return err
	}
	out.ProviderID = in.ProviderID
	return nil
}

// Convert_machine_MachineSpec_To_v1alpha1_MachineSpec is an autogenerated conversion function.
func Convert_machine_MachineSpec_To_v1alpha1_MachineSpec(in *machine.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	return autoConvert_machine_MachineSpec_To_v1alpha1_MachineSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineStatus_To_machine_MachineStatus(in *MachineStatus, out *machine.MachineStatus, s conversion.Scope) error {
	out.Node = in.Node
	out.Conditions = *(*[]v1.NodeCondition)(unsafe.Pointer(&in.Conditions))
	if err := Convert_v1alpha1_LastOperation_To_machine_LastOperation(&in.LastOperation, &out.LastOperation, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CurrentStatus_To_machine_CurrentStatus(&in.CurrentStatus, &out.CurrentStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineStatus_To_machine_MachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_MachineStatus_To_machine_MachineStatus(in *MachineStatus, out *machine.MachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineStatus_To_machine_MachineStatus(in, out, s)
}

func autoConvert_machine_MachineStatus_To_v1alpha1_MachineStatus(in *machine.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	out.Node = in.Node
	out.Conditions = *(*[]v1.NodeCondition)(unsafe.Pointer(&in.Conditions))
	if err := Convert_machine_LastOperation_To_v1alpha1_LastOperation(&in.LastOperation, &out.LastOperation, s); err != nil {
		return err
	}
	if err := Convert_machine_CurrentStatus_To_v1alpha1_CurrentStatus(&in.CurrentStatus, &out.CurrentStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_MachineStatus_To_v1alpha1_MachineStatus is an autogenerated conversion function.
func Convert_machine_MachineStatus_To_v1alpha1_MachineStatus(in *machine.MachineStatus, out *MachineStatus, s conversion.Scope) error {
	return autoConvert_machine_MachineStatus_To_v1alpha1_MachineStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineTemplate_To_machine_MachineTemplate(in *MachineTemplate, out *machine.MachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineTemplate_To_machine_MachineTemplate is an autogenerated conversion function.
func Convert_v1alpha1_MachineTemplate_To_machine_MachineTemplate(in *MachineTemplate, out *machine.MachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTemplate_To_machine_MachineTemplate(in, out, s)
}

func autoConvert_machine_MachineTemplate_To_v1alpha1_MachineTemplate(in *machine.MachineTemplate, out *MachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_MachineTemplate_To_v1alpha1_MachineTemplate is an autogenerated conversion function.
func Convert_machine_MachineTemplate_To_v1alpha1_MachineTemplate(in *machine.MachineTemplate, out *MachineTemplate, s conversion.Scope) error {
	return autoConvert_machine_MachineTemplate_To_v1alpha1_MachineTemplate(in, out, s)
}

func autoConvert_v1alpha1_MachineTemplateList_To_machine_MachineTemplateList(in *MachineTemplateList, out *machine.MachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]machine.MachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MachineTemplateList_To_machine_MachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_MachineTemplateList_To_machine_MachineTemplateList(in *MachineTemplateList, out *machine.MachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTemplateList_To_machine_MachineTemplateList(in, out, s)
}

func autoConvert_machine_MachineTemplateList_To_v1alpha1_MachineTemplateList(in *machine.MachineTemplateList, out *MachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_machine_MachineTemplateList_To_v1alpha1_MachineTemplateList is an autogenerated conversion function.
func Convert_machine_MachineTemplateList_To_v1alpha1_MachineTemplateList(in *machine.MachineTemplateList, out *MachineTemplateList, s conversion.Scope) error {
	return autoConvert_machine_MachineTemplateList_To_v1alpha1_MachineTemplateList(in, out, s)
}

func autoConvert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec(in *MachineTemplateSpec, out *machine.MachineTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSpec_To_machine_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec(in *MachineTemplateSpec, out *machine.MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineTemplateSpec_To_machine_MachineTemplateSpec(in, out, s)
}

func autoConvert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in *machine.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_machine_MachineSpec_To_v1alpha1_MachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec is an autogenerated conversion function.
func Convert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in *machine.MachineTemplateSpec, out *MachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_machine_MachineTemplateSpec_To_v1alpha1_MachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_RollbackConfig_To_machine_RollbackConfig(in *RollbackConfig, out *machine.RollbackConfig, s conversion.Scope) error {
	out.Revision = in.Revision
	return nil
}

// Convert_v1alpha1_RollbackConfig_To_machine_RollbackConfig is an autogenerated conversion function.
func Convert_v1alpha1_RollbackConfig_To_machine_RollbackConfig(in *RollbackConfig, out *machine.RollbackConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RollbackConfig_To_machine_RollbackConfig(in, out, s)
}

func autoConvert_machine_RollbackConfig_To_v1alpha1_RollbackConfig(in *machine.RollbackConfig, out *RollbackConfig, s conversion.Scope) error {
	out.Revision = in.Revision
	return nil
}

// Convert_machine_RollbackConfig_To_v1alpha1_RollbackConfig is an autogenerated conversion function.
func Convert_machine_RollbackConfig_To_v1alpha1_RollbackConfig(in *machine.RollbackConfig, out *RollbackConfig, s conversion.Scope) error {
	return autoConvert_machine_RollbackConfig_To_v1alpha1_RollbackConfig(in, out, s)
}

func autoConvert_v1alpha1_RollingUpdateMachineDeployment_To_machine_RollingUpdateMachineDeployment(in *RollingUpdateMachineDeployment, out *machine.RollingUpdateMachineDeployment, s conversion.Scope) error {
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_v1alpha1_RollingUpdateMachineDeployment_To_machine_RollingUpdateMachineDeployment is an autogenerated conversion function.
func Convert_v1alpha1_RollingUpdateMachineDeployment_To_machine_RollingUpdateMachineDeployment(in *RollingUpdateMachineDeployment, out *machine.RollingUpdateMachineDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_RollingUpdateMachineDeployment_To_machine_RollingUpdateMachineDeployment(in, out, s)
}

func autoConvert_machine_RollingUpdateMachineDeployment_To_v1alpha1_RollingUpdateMachineDeployment(in *machine.RollingUpdateMachineDeployment, out *RollingUpdateMachineDeployment, s conversion.Scope) error {
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	return nil
}

// Convert_machine_RollingUpdateMachineDeployment_To_v1alpha1_RollingUpdateMachineDeployment is an autogenerated conversion function.
func Convert_machine_RollingUpdateMachineDeployment_To_v1alpha1_RollingUpdateMachineDeployment(in *machine.RollingUpdateMachineDeployment, out *RollingUpdateMachineDeployment, s conversion.Scope) error {
	return autoConvert_machine_RollingUpdateMachineDeployment_To_v1alpha1_RollingUpdateMachineDeployment(in, out, s)
}

func autoConvert_v1alpha1_Scale_To_machine_Scale(in *Scale, out *machine.Scale, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ScaleSpec_To_machine_ScaleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ScaleStatus_To_machine_ScaleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Scale_To_machine_Scale is an autogenerated conversion function.
func Convert_v1alpha1_Scale_To_machine_Scale(in *Scale, out *machine.Scale, s conversion.Scope) error {
	return autoConvert_v1alpha1_Scale_To_machine_Scale(in, out, s)
}

func autoConvert_machine_Scale_To_v1alpha1_Scale(in *machine.Scale, out *Scale, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_machine_ScaleSpec_To_v1alpha1_ScaleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_machine_ScaleStatus_To_v1alpha1_ScaleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_machine_Scale_To_v1alpha1_Scale is an autogenerated conversion function.
func Convert_machine_Scale_To_v1alpha1_Scale(in *machine.Scale, out *Scale, s conversion.Scope) error {
	return autoConvert_machine_Scale_To_v1alpha1_Scale(in, out, s)
}

func autoConvert_v1alpha1_ScaleSpec_To_machine_ScaleSpec(in *ScaleSpec, out *machine.ScaleSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	return nil
}

// Convert_v1alpha1_ScaleSpec_To_machine_ScaleSpec is an autogenerated conversion function.
func Convert_v1alpha1_ScaleSpec_To_machine_ScaleSpec(in *ScaleSpec, out *machine.ScaleSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScaleSpec_To_machine_ScaleSpec(in, out, s)
}

func autoConvert_machine_ScaleSpec_To_v1alpha1_ScaleSpec(in *machine.ScaleSpec, out *ScaleSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	return nil
}

// Convert_machine_ScaleSpec_To_v1alpha1_ScaleSpec is an autogenerated conversion function.
func Convert_machine_ScaleSpec_To_v1alpha1_ScaleSpec(in *machine.ScaleSpec, out *ScaleSpec, s conversion.Scope) error {
	return autoConvert_machine_ScaleSpec_To_v1alpha1_ScaleSpec(in, out, s)
}

func autoConvert_v1alpha1_ScaleStatus_To_machine_ScaleStatus(in *ScaleStatus, out *machine.ScaleStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.TargetSelector = in.TargetSelector
	return nil
}

// Convert_v1alpha1_ScaleStatus_To_machine_ScaleStatus is an autogenerated conversion function.
func Convert_v1alpha1_ScaleStatus_To_machine_ScaleStatus(in *ScaleStatus, out *machine.ScaleStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScaleStatus_To_machine_ScaleStatus(in, out, s)
}

func autoConvert_machine_ScaleStatus_To_v1alpha1_ScaleStatus(in *machine.ScaleStatus, out *ScaleStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.TargetSelector = in.TargetSelector
	return nil
}

// Convert_machine_ScaleStatus_To_v1alpha1_ScaleStatus is an autogenerated conversion function.
func Convert_machine_ScaleStatus_To_v1alpha1_ScaleStatus(in *machine.ScaleStatus, out *ScaleStatus, s conversion.Scope) error {
	return autoConvert_machine_ScaleStatus_To_v1alpha1_ScaleStatus(in, out, s)
}
